CREATE TYPE [dbo].[TMSData_Old] AS TABLE (
    [PROG_AIR_DT]        DATETIME      NULL,
    [PROG_START_TIME]    VARCHAR (5)   NULL,
    [PROG_TMS_CHANNEL]   VARCHAR (6)   NULL,
    [PROG_NAME]          VARCHAR (MAX) NULL,
    [PROG_DURATION]      NUMERIC (3)   NULL,
    [PROG_SOURCE_TYPE]   CHAR (1)      NULL,
    [PROG_SYNDICATOR_ID] VARCHAR (15)  NULL,
    [PROG_EPISODE_ID]    VARCHAR (20)  NULL,
    [PROG_EPISODE_NAME]  VARCHAR (MAX) NULL);

