CREATE TABLE [dbo].[AcctMapLog] (
    [LogTimeStamp]            DATETIME     NULL,
    [LogDMLOperation]         CHAR (1)     NULL,
    [LoginUser]               VARCHAR (32) NULL,
    [AcctMapID]               INT          NULL,
    [RCSAcctID]               INT          NULL,
    [OldVal_RCSAcctID]        INT          NULL,
    [AcctName]                VARCHAR (50) NULL,
    [OldVal_AcctName]         VARCHAR (50) NULL,
    [RCSAdvID]                INT          NULL,
    [OldVal_RCSAdvID]         INT          NULL,
    [AdvID]                   INT          NULL,
    [OldVal_AdvID]            INT          NULL,
    [Priority]                INT          NULL,
    [OldVal_Priority]         INT          NULL,
    [AutoIndexing]            TINYINT      NULL,
    [OldVal_AutoIndexing]     TINYINT      NULL,
    [Deleted]                 TINYINT      NULL,
    [OldVal_Deleted]          TINYINT      NULL,
    [CreatedDT]               DATETIME     NULL,
    [OldVal_CreatedDT]        DATETIME     NULL,
    [CreatedByID]             INT          NULL,
    [OldVal_CreatedByID]      INT          NULL,
    [ModifiedDT]              DATETIME     NULL,
    [OldVal_ModifiedDT]       DATETIME     NULL,
    [ModifiedByID]            INT          NULL,
    [OldVal_ModifiedByID]     INT          NULL,
    [CTLegacyID]              INT          NULL,
    [OldVal_CTLegacyID]       INT          NULL,
    [CTLegacyInstCode]        VARCHAR (6)  NULL,
    [OldVal_CTLegacyInstCode] VARCHAR (6)  NULL,
    CHECK ([LogDMLOperation]='U' OR [LogDMLOperation]='I' OR [LogDMLOperation]='D')
);

