CREATE TABLE [dbo].[AdLogTest] (
    [LogTimeStamp]                 DATETIME       NULL,
    [LogDMLOperation]              CHAR (1)       NULL,
    [LoginUser]                    VARCHAR (32)   NULL,
    [AdID]                         INT            NULL,
    [OriginalAdID]                 INT            NULL,
    [OldVal_OriginalAdID]          INT            NULL,
    [PrimaryOccurrenceID]          VARCHAR (8000) NULL,
    [OldVal_PrimaryOccurrenceID]   VARCHAR (8000) NULL,
    [AdvertiserID]                 INT            NULL,
    [OldVal_AdvertiserID]          INT            NULL,
    [BreakDT]                      DATETIME       NULL,
    [OldVal_BreakDT]               DATETIME       NULL,
    [StartDT]                      DATETIME       NULL,
    [OldVal_StartDT]               DATETIME       NULL,
    [EndDT]                        DATETIME       NULL,
    [OldVal_EndDT]                 DATETIME       NULL,
    [LanguageID]                   INT            NULL,
    [OldVal_LanguageID]            INT            NULL,
    [FamilyID]                     INT            NULL,
    [OldVal_FamilyID]              INT            NULL,
    [CommonAdDT]                   DATETIME       NULL,
    [OldVal_CommonAdDT]            DATETIME       NULL,
    [NoTakeAdReason]               INT            NULL,
    [OldVal_NoTakeAdReason]        INT            NULL,
    [FirstRunMarket]               VARCHAR (8000) NULL,
    [OldVal_FirstRunMarket]        VARCHAR (8000) NULL,
    [FirstRunDate]                 DATETIME       NULL,
    [OldVal_FirstRunDate]          DATETIME       NULL,
    [LastRunDate]                  DATETIME       NULL,
    [OldVal_LastRunDate]           DATETIME       NULL,
    [AdName]                       VARCHAR (8000) NULL,
    [OldVal_AdName]                VARCHAR (8000) NULL,
    [AdVisual]                     VARCHAR (8000) NULL,
    [OldVal_AdVisual]              VARCHAR (8000) NULL,
    [AdInfo]                       VARCHAR (8000) NULL,
    [OldVal_AdInfo]                VARCHAR (8000) NULL,
    [Coop1AdvId]                   VARCHAR (8000) NULL,
    [OldVal_Coop1AdvId]            VARCHAR (8000) NULL,
    [Coop2AdvId]                   VARCHAR (8000) NULL,
    [OldVal_Coop2AdvId]            VARCHAR (8000) NULL,
    [Coop3AdvId]                   VARCHAR (8000) NULL,
    [OldVal_Coop3AdvId]            VARCHAR (8000) NULL,
    [Comp1AdvId]                   VARCHAR (8000) NULL,
    [OldVal_Comp1AdvId]            VARCHAR (8000) NULL,
    [Comp2AdvId]                   VARCHAR (8000) NULL,
    [OldVal_Comp2AdvId]            VARCHAR (8000) NULL,
    [TaglineId]                    VARCHAR (8000) NULL,
    [OldVal_TaglineId]             VARCHAR (8000) NULL,
    [LeadText]                     VARCHAR (8000) NULL,
    [OldVal_LeadText]              VARCHAR (8000) NULL,
    [LeadAvHeadline]               VARCHAR (8000) NULL,
    [OldVal_LeadAvHeadline]        VARCHAR (8000) NULL,
    [RecutDetail]                  VARCHAR (8000) NULL,
    [OldVal_RecutDetail]           VARCHAR (8000) NULL,
    [RecutAdId]                    INT            NULL,
    [OldVal_RecutAdId]             INT            NULL,
    [EthnicFlag]                   VARCHAR (8000) NULL,
    [OldVal_EthnicFlag]            VARCHAR (8000) NULL,
    [AddlInfo]                     VARCHAR (8000) NULL,
    [OldVal_AddlInfo]              VARCHAR (8000) NULL,
    [AdLength]                     INT            NULL,
    [OldVal_AdLength]              INT            NULL,
    [InternalNotes]                VARCHAR (8000) NULL,
    [OldVal_InternalNotes]         VARCHAR (8000) NULL,
    [ProductId]                    INT            NULL,
    [OldVal_ProductId]             INT            NULL,
    [Description]                  VARCHAR (8000) NULL,
    [OldVal_Description]           VARCHAR (8000) NULL,
    [SessionDate]                  DATETIME       NULL,
    [OldVal_SessionDate]           DATETIME       NULL,
    [Unclassified]                 BIT            NULL,
    [OldVal_Unclassified]          BIT            NULL,
    [CreateDate]                   DATETIME       NULL,
    [OldVal_CreateDate]            DATETIME       NULL,
    [CreatedBy]                    INT            NULL,
    [OldVal_CreatedBy]             INT            NULL,
    [ModifiedDate]                 DATETIME       NULL,
    [OldVal_ModifiedDate]          DATETIME       NULL,
    [ModifiedBy]                   INT            NULL,
    [OldVal_ModifiedBy]            INT            NULL,
    [Campaign]                     VARCHAR (8000) NULL,
    [OldVal_Campaign]              VARCHAR (8000) NULL,
    [KeyVisualElement]             VARCHAR (8000) NULL,
    [OldVal_KeyVisualElement]      VARCHAR (8000) NULL,
    [EntryEligible]                VARCHAR (8000) NULL,
    [OldVal_EntryEligible]         VARCHAR (8000) NULL,
    [AdType]                       VARCHAR (8000) NULL,
    [OldVal_AdType]                VARCHAR (8000) NULL,
    [AdDistribution]               VARCHAR (8000) NULL,
    [OldVal_AdDistribution]        VARCHAR (8000) NULL,
    [ClassifiedBy]                 VARCHAR (8000) NULL,
    [OldVal_ClassifiedBy]          VARCHAR (8000) NULL,
    [ClassifiedDT]                 DATETIME       NULL,
    [OldVal_ClassifiedDT]          DATETIME       NULL,
    [MarketID]                     INT            NULL,
    [OldVal_MarketID]              INT            NULL,
    [Query]                        INT            NULL,
    [OldVal_Query]                 INT            NULL,
    [AuditedByID]                  VARCHAR (8000) NULL,
    [OldVal_AuditedByID]           VARCHAR (8000) NULL,
    [AuditDT]                      DATE           NULL,
    [OldVal_AuditDT]               DATE           NULL,
    [CelebrityID]                  INT            NULL,
    [OldVal_CelebrityID]           INT            NULL,
    [ClassificationGroupID]        INT            NULL,
    [OldVal_ClassificationGroupID] INT            NULL,
    [CTLegacySEQ]                  INT            NULL,
    [OldVal_CTLegacySEQ]           INT            NULL,
    [CTLegacyAdCode]               VARCHAR (12)   NULL,
    [OldVal_CTLegacyAdCode]        VARCHAR (12)   NULL
);

