CREATE TABLE [dbo].[AdLogStaging] (
    [LogTimeStamp]                 DATETIME       NULL,
    [LogDMLOperation]              CHAR (1)       NULL,
    [LoginUser]                    VARCHAR (32)   NULL,
    [AdID]                         INT            NULL,
    [OriginalAdID]                 INT            NULL,
    [OldVal_OriginalAdID]          INT            NULL,
    [PrimaryOccurrenceID]          NVARCHAR (MAX) NULL,
    [OldVal_PrimaryOccurrenceID]   NVARCHAR (MAX) NULL,
    [AdvertiserID]                 INT            NULL,
    [OldVal_AdvertiserID]          INT            NULL,
    [BreakDT]                      DATETIME       NULL,
    [OldVal_BreakDT]               DATETIME       NULL,
    [StartDT]                      DATETIME       NULL,
    [OldVal_StartDT]               DATETIME       NULL,
    [EndDT]                        DATETIME       NULL,
    [OldVal_EndDT]                 DATETIME       NULL,
    [LanguageID]                   INT            NULL,
    [OldVal_LanguageID]            INT            NULL,
    [FamilyID]                     INT            NULL,
    [OldVal_FamilyID]              INT            NULL,
    [CommonAdDT]                   DATETIME       NULL,
    [OldVal_CommonAdDT]            DATETIME       NULL,
    [NoTakeAdReason]               INT            NULL,
    [OldVal_NoTakeAdReason]        INT            NULL,
    [FirstRunMarket]               NVARCHAR (MAX) NULL,
    [OldVal_FirstRunMarket]        NVARCHAR (MAX) NULL,
    [FirstRunDate]                 DATETIME       NULL,
    [OldVal_FirstRunDate]          DATETIME       NULL,
    [LastRunDate]                  DATETIME       NULL,
    [OldVal_LastRunDate]           DATETIME       NULL,
    [AdName]                       NVARCHAR (MAX) NULL,
    [OldVal_AdName]                NVARCHAR (MAX) NULL,
    [AdVisual]                     NVARCHAR (MAX) NULL,
    [OldVal_AdVisual]              NVARCHAR (MAX) NULL,
    [AdInfo]                       NVARCHAR (MAX) NULL,
    [OldVal_AdInfo]                NVARCHAR (MAX) NULL,
    [Coop1AdvId]                   NVARCHAR (MAX) NULL,
    [OldVal_Coop1AdvId]            NVARCHAR (MAX) NULL,
    [Coop2AdvId]                   NVARCHAR (MAX) NULL,
    [OldVal_Coop2AdvId]            NVARCHAR (MAX) NULL,
    [Coop3AdvId]                   NVARCHAR (MAX) NULL,
    [OldVal_Coop3AdvId]            NVARCHAR (MAX) NULL,
    [Comp1AdvId]                   NVARCHAR (MAX) NULL,
    [OldVal_Comp1AdvId]            NVARCHAR (MAX) NULL,
    [Comp2AdvId]                   NVARCHAR (MAX) NULL,
    [OldVal_Comp2AdvId]            NVARCHAR (MAX) NULL,
    [TaglineId]                    NVARCHAR (MAX) NULL,
    [OldVal_TaglineId]             NVARCHAR (MAX) NULL,
    [LeadText]                     NVARCHAR (MAX) NULL,
    [OldVal_LeadText]              NVARCHAR (MAX) NULL,
    [LeadAvHeadline]               NVARCHAR (MAX) NULL,
    [OldVal_LeadAvHeadline]        NVARCHAR (MAX) NULL,
    [RecutDetail]                  NVARCHAR (MAX) NULL,
    [OldVal_RecutDetail]           NVARCHAR (MAX) NULL,
    [RecutAdId]                    INT            NULL,
    [OldVal_RecutAdId]             INT            NULL,
    [EthnicFlag]                   NVARCHAR (MAX) NULL,
    [OldVal_EthnicFlag]            NVARCHAR (MAX) NULL,
    [AddlInfo]                     NVARCHAR (MAX) NULL,
    [OldVal_AddlInfo]              NVARCHAR (MAX) NULL,
    [AdLength]                     INT            NULL,
    [OldVal_AdLength]              INT            NULL,
    [InternalNotes]                NVARCHAR (MAX) NULL,
    [OldVal_InternalNotes]         NVARCHAR (MAX) NULL,
    [ProductId]                    INT            NULL,
    [OldVal_ProductId]             INT            NULL,
    [Description]                  NVARCHAR (MAX) NULL,
    [OldVal_Description]           NVARCHAR (MAX) NULL,
    [SessionDate]                  DATETIME       NULL,
    [OldVal_SessionDate]           DATETIME       NULL,
    [Unclassified]                 BIT            NULL,
    [OldVal_Unclassified]          BIT            NULL,
    [CreateDate]                   DATETIME       NULL,
    [OldVal_CreateDate]            DATETIME       NULL,
    [CreatedBy]                    INT            NULL,
    [OldVal_CreatedBy]             INT            NULL,
    [ModifiedDate]                 DATETIME       NULL,
    [OldVal_ModifiedDate]          DATETIME       NULL,
    [ModifiedBy]                   INT            NULL,
    [OldVal_ModifiedBy]            INT            NULL,
    [Campaign]                     NVARCHAR (MAX) NULL,
    [OldVal_Campaign]              NVARCHAR (MAX) NULL,
    [KeyVisualElement]             NVARCHAR (MAX) NULL,
    [OldVal_KeyVisualElement]      NVARCHAR (MAX) NULL,
    [EntryEligible]                NVARCHAR (MAX) NULL,
    [OldVal_EntryEligible]         NVARCHAR (MAX) NULL,
    [AdType]                       NVARCHAR (MAX) NULL,
    [OldVal_AdType]                NVARCHAR (MAX) NULL,
    [AdDistribution]               NVARCHAR (MAX) NULL,
    [OldVal_AdDistribution]        NVARCHAR (MAX) NULL,
    [ClassifiedBy]                 NVARCHAR (MAX) NULL,
    [OldVal_ClassifiedBy]          NVARCHAR (MAX) NULL,
    [ClassifiedDT]                 DATETIME       NULL,
    [OldVal_ClassifiedDT]          DATETIME       NULL,
    [MarketID]                     INT            NULL,
    [OldVal_MarketID]              INT            NULL,
    [Query]                        INT            NULL,
    [OldVal_Query]                 INT            NULL,
    [AuditedByID]                  NVARCHAR (MAX) NULL,
    [OldVal_AuditedByID]           NVARCHAR (MAX) NULL,
    [AuditDT]                      DATE           NULL,
    [OldVal_AuditDT]               DATE           NULL,
    [CelebrityID]                  INT            NULL,
    [OldVal_CelebrityID]           INT            NULL,
    [ClassificationGroupID]        INT            NULL,
    [OldVal_ClassificationGroupID] INT            NULL,
    [CTLegacySEQ]                  INT            NULL,
    [OldVal_CTLegacySEQ]           INT            NULL,
    [CTLegacyAdCode]               VARCHAR (12)   NULL,
    [OldVal_CTLegacyAdCode]        VARCHAR (12)   NULL
);

