CREATE TABLE [dbo].[AdvertiserLog] (
    [LogTimeStamp]               DATETIME      NULL,
    [LogDMLOperation]            CHAR (1)      NULL,
    [LoginUser]                  VARCHAR (32)  NULL,
    [AdvertiserID]               INT           NULL,
    [Descrip]                    VARCHAR (50)  NULL,
    [OldVal_Descrip]             VARCHAR (50)  NULL,
    [ShortName]                  VARCHAR (50)  NULL,
    [OldVal_ShortName]           VARCHAR (50)  NULL,
    [TradeClassID]               INT           NULL,
    [OldVal_TradeClassID]        INT           NULL,
    [StartDT]                    DATETIME      NULL,
    [OldVal_StartDT]             DATETIME      NULL,
    [EndDT]                      DATETIME      NULL,
    [OldVal_EndDT]               DATETIME      NULL,
    [Priority]                   INT           NULL,
    [OldVal_Priority]            INT           NULL,
    [LanguageID]                 INT           NULL,
    [OldVal_LanguageID]          INT           NULL,
    [AdvertiserComments]         VARCHAR (250) NULL,
    [OldVal_AdvertiserComments]  VARCHAR (250) NULL,
    [Address1]                   VARCHAR (MAX) NULL,
    [OldVal_Address1]            VARCHAR (MAX) NULL,
    [Address2]                   VARCHAR (MAX) NULL,
    [OldVal_Address2]            VARCHAR (MAX) NULL,
    [City]                       VARCHAR (MAX) NULL,
    [OldVal_City]                VARCHAR (MAX) NULL,
    [State]                      VARCHAR (MAX) NULL,
    [OldVal_State]               VARCHAR (MAX) NULL,
    [ZipCode]                    VARCHAR (MAX) NULL,
    [OldVal_ZipCode]             VARCHAR (MAX) NULL,
    [CreatedDT]                  DATETIME      NULL,
    [OldVal_CreatedDT]           DATETIME      NULL,
    [CreatedByID]                INT           NULL,
    [OldVal_CreatedByID]         INT           NULL,
    [ModifiedDT]                 DATETIME      NULL,
    [OldVal_ModifiedDT]          DATETIME      NULL,
    [ModifiedByID]               INT           NULL,
    [OldVal_ModifiedByID]        INT           NULL,
    [IndustryID]                 INT           NULL,
    [OldVal_IndustryID]          INT           NULL,
    [ParentAdvertiserID]         INT           NULL,
    [OldVal_ParentAdvertiserID]  INT           NULL,
    [CTLegacyINSTCOD]            VARCHAR (6)   NULL,
    [OldVal_CTLegacyINSTCOD]     VARCHAR (6)   NULL,
    [MTLegacyRetID]              INT           NULL,
    [OldVal_MTLegacyRetID]       INT           NULL,
    [CTLegacyINSEQ]              INT           NULL,
    [OldVal_CTLegacyINSEQ]       INT           NULL,
    [CTLegacyINSTATE]            VARCHAR (9)   NULL,
    [OldVal_CTLegacyINSTATE]     VARCHAR (9)   NULL,
    [CTLegacyINCNTRY]            VARCHAR (3)   NULL,
    [OldVal_CTLegacyINCNTRY]     VARCHAR (3)   NULL,
    [CTLegacyINPARENT]           VARCHAR (20)  NULL,
    [OldVal_CTLegacyINPARENT]    VARCHAR (20)  NULL,
    [CTLegacyINSHORTNAME]        VARCHAR (35)  NULL,
    [OldVal_CTLegacyINSHORTNAME] VARCHAR (35)  NULL,
    [MTLegacyLanguageID]         INT           NULL,
    [OldVal_MTLegacyLanguageID]  INT           NULL,
    [MTLegacyPriority]           INT           NULL,
    [OldVal_MTLegacyPriority]    INT           NULL,
    CHECK ([LogDMLOperation]='U' OR [LogDMLOperation]='I' OR [LogDMLOperation]='D')
);

