CREATE TABLE [dbo].[COMWebsiteExtSrcMapLog] (
    [LogTimeStamp]          DATETIME      NULL,
    [LogDMLOperation]       CHAR (1)      NULL,
    [LoginUser]             VARCHAR (32)  NULL,
    [COMWebsiteExtSrcMapID] INT           NULL,
    [SiteID]                INT           NULL,
    [OldVal_SiteID]         INT           NULL,
    [ExtSrcName]            VARCHAR (MAX) NULL,
    [OldVal_ExtSrcName]     VARCHAR (MAX) NULL,
    [ExtSrcID]              INT           NULL,
    [OldVal_ExtSrcID]       INT           NULL,
    [ExtSrcStartDT]         DATE          NULL,
    [OldVal_ExtSrcStartDT]  DATE          NULL,
    [ExtSrcEndDT]           DATE          NULL,
    [OldVal_ExtSrcEndDT]    DATE          NULL,
    [Comments]              VARCHAR (MAX) NULL,
    [OldVal_Comments]       VARCHAR (MAX) NULL,
    [CreatedDT]             DATE          NULL,
    [OldVal_CreatedDT]      DATE          NULL,
    [CreatedByID]           INT           NULL,
    [OldVal_CreatedByID]    INT           NULL,
    [ModifiedDT]            DATE          NULL,
    [OldVal_ModifiedDT]     DATE          NULL,
    [ModifiedByID]          INT           NULL,
    [OldVal_ModifiedByID]   INT           NULL,
    CHECK ([LogDMLOperation]='U' OR [LogDMLOperation]='I' OR [LogDMLOperation]='D')
);

