CREATE TABLE [dbo].[CreativeContentDetailLog] (
    [LogTimeStamp]                DATETIME     NULL,
    [LogDMLOperation]             CHAR (1)     NULL,
    [LoginUser]                   VARCHAR (32) NULL,
    [CreativeContentDetailID]     INT          NULL,
    [CreativeCropID]              INT          NULL,
    [OldVal_CreativeCropID]       INT          NULL,
    [CreativeDetailID]            INT          NULL,
    [OldVal_CreativeDetailID]     INT          NULL,
    [SellableSpaceCoordX1]        INT          NULL,
    [OldVal_SellableSpaceCoordX1] INT          NULL,
    [SellableSpaceCoordY1]        INT          NULL,
    [OldVal_SellableSpaceCoordY1] INT          NULL,
    [SellableSpaceCoordX2]        INT          NULL,
    [OldVal_SellableSpaceCoordX2] INT          NULL,
    [SellableSpaceCoordY2]        INT          NULL,
    [OldVal_SellableSpaceCoordY2] INT          NULL,
    [SellableSpaceArea]           INT          NULL,
    [OldVal_SellableSpaceArea]    INT          NULL,
    [CompletedByID]               INT          NULL,
    [OldVal_CompletedByID]        INT          NULL,
    [CompletedDT]                 DATETIME     NULL,
    [OldVal_CompletedDT]          DATETIME     NULL,
    [CreatedDT]                   DATETIME     NULL,
    [OldVal_CreatedDT]            DATETIME     NULL,
    [CreatedByID]                 INT          NULL,
    [OldVal_CreatedByID]          INT          NULL,
    [ModifiedDT]                  DATETIME     NULL,
    [OldVal_ModifiedDT]           DATETIME     NULL,
    [ModifiedByID]                INT          NULL,
    [OldVal_ModifiedByID]         INT          NULL,
    CHECK ([LogDMLOperation]='U' OR [LogDMLOperation]='I' OR [LogDMLOperation]='D')
);

