CREATE TABLE [dbo].[CreativeModificationsLog] (
    [LogTimeStamp]                    DATETIME      NULL,
    [LogDMLOperation]                 CHAR (1)      NULL,
    [LoginUser]                       VARCHAR (32)  NULL,
    [CreativeModificationId]          BIGINT        NULL,
    [OldValue_CreativeModificationId] BIGINT        NULL,
    [AdId]                            BIGINT        NULL,
    [OldValue_AdId]                   BIGINT        NULL,
    [CreativeId]                      BIGINT        NULL,
    [OldValue_CreativeId]             BIGINT        NULL,
    [OccurrenceId]                    BIGINT        NULL,
    [OldValue_OccurrenceId]           BIGINT        NULL,
    [CreativeSignature]               VARCHAR (200) NULL,
    [OldValue_CreativeSignature]      VARCHAR (200) NULL,
    [CreativePath]                    VARCHAR (200) NULL,
    [OldValue_CreativePath]           VARCHAR (200) NULL,
    [ModifiedById]                    INT           NULL,
    [OldValue_ModifiedById]           INT           NULL,
    [ModifiedDT]                      DATETIME      NULL,
    [OldValue_ModifiedDT]             DATETIME      NULL,
    [MediaStreamId]                   INT           NULL,
    [OldValue_MediaStreamId]          INT           NULL,
    [LocationId]                      INT           NULL,
    [OldValue_LocationId]             INT           NULL,
    [Synced]                          BIT           NULL,
    [OldValue_Synced]                 BIT           NULL,
    [SyncDT]                          DATETIME      NULL,
    [OldValue_SyncDT]                 DATETIME      NULL,
    CHECK ([LogDMLOperation]='U' OR [LogDMLOperation]='I' OR [LogDMLOperation]='D')
);

