CREATE TABLE [dbo].[CreativeLog] (
    [LogTimeStamp]                 DATETIME       NULL,
    [LogDMLOperation]              CHAR (1)       NULL,
    [LoginUser]                    VARCHAR (32)   NULL,
    [PK_Id]                        INT            NULL,
    [AdId]                         INT            NULL,
    [OldVal_AdId]                  INT            NULL,
    [SourceOccurrenceId]           INT            NULL,
    [OldVal_SourceOccurrenceId]    INT            NULL,
    [EnvelopId]                    INT            NULL,
    [OldVal_EnvelopId]             INT            NULL,
    [PrimaryIndicator]             BIT            NULL,
    [OldVal_PrimaryIndicator]      BIT            NULL,
    [PrimaryQuality]               INT            NULL,
    [OldVal_PrimaryQuality]        INT            NULL,
    [CreativeType]                 VARCHAR (MAX)  NULL,
    [OldVal_CreativeType]          VARCHAR (MAX)  NULL,
    [StatusId]                     INT            NULL,
    [OldVal_StatusId]              INT            NULL,
    [PullPageCount]                INT            NULL,
    [OldVal_PullPageCount]         INT            NULL,
    [Weight]                       FLOAT (53)     NULL,
    [OldVal_Weight]                FLOAT (53)     NULL,
    [FormName]                     VARCHAR (100)  NULL,
    [OldVal_FormName]              VARCHAR (100)  NULL,
    [CheckInOccrncs]               INT            NULL,
    [OldVal_CheckInOccrncs]        INT            NULL,
    [SpReviewStatusId]             INT            NULL,
    [OldVal_SpReviewStatusId]      INT            NULL,
    [EntryInd]                     INT            NULL,
    [OldVal_EntryInd]              INT            NULL,
    [ParentVehicleId]              INT            NULL,
    [OldVal_ParentVehicleId]       INT            NULL,
    [FilterMatches]                VARCHAR (100)  NULL,
    [OldVal_FilterMatches]         VARCHAR (100)  NULL,
    [SourceMatchInd]               INT            NULL,
    [OldVal_SourceMatchInd]        INT            NULL,
    [TypeId]                       INT            NULL,
    [OldVal_TypeId]                INT            NULL,
    [FlashInd]                     INT            NULL,
    [OldVal_FlashInd]              INT            NULL,
    [CouponInd]                    INT            NULL,
    [OldVal_CouponInd]             INT            NULL,
    [Priority]                     INT            NULL,
    [OldVal_Priority]              INT            NULL,
    [NationalInd]                  INT            NULL,
    [OldVal_NationalInd]           INT            NULL,
    [DistDate]                     DATETIME       NULL,
    [OldVal_DistDate]              DATETIME       NULL,
    [Cini]                         VARCHAR (50)   NULL,
    [OldVal_Cini]                  VARCHAR (50)   NULL,
    [Erin]                         VARCHAR (50)   NULL,
    [OldVal_Erin]                  VARCHAR (50)   NULL,
    [Init]                         VARCHAR (50)   NULL,
    [OldVal_Init]                  VARCHAR (50)   NULL,
    [AssetThmbnlName]              VARCHAR (1000) NULL,
    [OldVal_AssetThmbnlName]       VARCHAR (1000) NULL,
    [ThmbnlRep]                    VARCHAR (1000) NULL,
    [OldVal_ThmbnlRep]             VARCHAR (1000) NULL,
    [LegacyThmbnlAssetName]        VARCHAR (50)   NULL,
    [OldVal_LegacyThmbnlAssetName] VARCHAR (50)   NULL,
    [ThmbnlFileType]               VARCHAR (50)   NULL,
    [OldVal_ThmbnlFileType]        VARCHAR (50)   NULL,
    [CreatedDT]                    DATETIME       NULL,
    [OldVal_CreatedDT]             DATETIME       NULL,
    CHECK ([LogDMLOperation]='U' OR [LogDMLOperation]='I' OR [LogDMLOperation]='D')
);

