CREATE TABLE [dbo].[CreativeStagingLog] (
    [LogTimeStamp]             DATETIME       NULL,
    [LogDMLOperation]          CHAR (1)       NULL,
    [LoginUser]                VARCHAR (32)   NULL,
    [CreativeStagingID]        INT            NULL,
    [AdID]                     INT            NULL,
    [OldVal_AdID]              INT            NULL,
    [Deleted]                  BIT            NULL,
    [OldVal_Deleted]           BIT            NULL,
    [Event]                    INT            NULL,
    [OldVal_Event]             INT            NULL,
    [Theme]                    INT            NULL,
    [OldVal_Theme]             INT            NULL,
    [SaleStartDT]              DATETIME       NULL,
    [OldVal_SaleStartDT]       DATETIME       NULL,
    [SaleEndDT]                DATETIME       NULL,
    [OldVal_SaleEndDT]         DATETIME       NULL,
    [Flash]                    BIT            NULL,
    [OldVal_Flash]             BIT            NULL,
    [National]                 BIT            NULL,
    [OldVal_National]          BIT            NULL,
    [CreatedDT]                DATETIME       NULL,
    [OldVal_CreatedDT]         DATETIME       NULL,
    [DeleteDT]                 DATETIME       NULL,
    [OldVal_DeleteDT]          DATETIME       NULL,
    [OccurrenceID]             INT            NULL,
    [OldVal_OccurrenceID]      INT            NULL,
    [CreativeSignature]        VARCHAR (250)  NULL,
    [OldVal_CreativeSignature] VARCHAR (250)  NULL,
    [OldID]                    INT            NULL,
    [OldVal_OldID]             INT            NULL,
    [PatternID]                INT            NULL,
    [OldVal_PatternID]         INT            NULL,
    [OldVal_CreativeStagingID] INT            NULL,
    [AssetThmbnlName]          VARCHAR (1000) NULL,
    [OldVal_AssetThmbnlName]   VARCHAR (1000) NULL,
    [ThmbnlRep]                VARCHAR (1000) NULL,
    [OldVal_ThmbnlRep]         VARCHAR (1000) NULL,
    [ThmbnlFileType]           VARCHAR (50)   NULL,
    [OldVal_ThmbnlFileType]    VARCHAR (50)   NULL,
    CHECK ([LogDMLOperation]='U' OR [LogDMLOperation]='I' OR [LogDMLOperation]='D')
);

