CREATE TABLE [dbo].[EndState-Excpectation-NoFillFilter] (
    [ExpectationId (Alan new)] VARCHAR (200) NULL,
    [ExpectationID (old)]      VARCHAR (200) NULL,
    [Advertiser]               VARCHAR (200) NULL,
    [Mkt]                      VARCHAR (200) NULL,
    [Country of Origin (new)]  VARCHAR (200) NULL,
    [Media Type]               VARCHAR (200) NULL,
    [Kim Comment]              VARCHAR (500) NULL,
    [RetId]                    VARCHAR (200) NULL,
    [MktId]                    VARCHAR (200) NULL,
    [MediaId]                  VARCHAR (200) NULL,
    [Priority]                 VARCHAR (200) NULL,
    [FrequencyId]              VARCHAR (200) NULL,
    [StartDt]                  VARCHAR (200) NULL,
    [EndDt]                    VARCHAR (200) NULL,
    [Media Comments]           VARCHAR (500) NULL,
    [MissingAdComments]        VARCHAR (500) NULL,
    [ScanDPI]                  VARCHAR (200) NULL,
    [rowguid]                  VARCHAR (200) NULL,
    [Brand (CT)]               VARCHAR (200) NULL,
    [AdDynReqInd]              VARCHAR (200) NULL,
    [AdSmtReqInd]              VARCHAR (200) NULL,
    [ScanReqInd]               VARCHAR (200) NULL,
    [jaAlcInd]                 VARCHAR (200) NULL,
    [jaAlcMInd]                VARCHAR (200) NULL,
    [jaAlcVInd]                VARCHAR (200) NULL,
    [jaallInd]                 VARCHAR (200) NULL,
    [jaAllmInd]                VARCHAR (200) NULL,
    [jaAllvInd]                VARCHAR (200) NULL,
    [jaasmInd]                 VARCHAR (200) NULL,
    [jabevInd]                 VARCHAR (200) NULL,
    [jacanInd]                 VARCHAR (200) NULL,
    [jafrVInd]                 VARCHAR (200) NULL,
    [jaHSPeInd]                VARCHAR (200) NULL,
    [jaHSPsInd]                VARCHAR (200) NULL,
    [jalnetInd]                VARCHAR (200) NULL,
    [jamassInd]                VARCHAR (200) NULL,
    [jaspanInd]                VARCHAR (200) NULL,
    [email]                    VARCHAR (200) NULL,
    [ROPPageNameInd]           VARCHAR (200) NULL,
    [FVEntry360Ind]            VARCHAR (200) NULL,
    [IndAutoQC]                VARCHAR (200) NULL
);

