CREATE TABLE [dbo].[EndStateCaptureStationCodeDecoding] (
    [STPS_STAT_CODE]           VARCHAR (50) NULL,
    [CST_CAPTURE_STATION_CODE] VARCHAR (50) NULL,
    [CSM_CAPTURE_STATION]      VARCHAR (50) NULL
);

