CREATE TABLE [dbo].[EndState-ElementCriteriaCondition] (
    [PK_CriteriaConditionID] VARCHAR (50)   NULL,
    [FK_CriteriaID]          VARCHAR (50)   NULL,
    [CriteriaTitle]          VARCHAR (200)  NULL,
    [CompoundORIndicator]    VARCHAR (50)   NULL,
    [FK_ConditionID]         VARCHAR (50)   NULL,
    [ConditionIDList]        VARCHAR (50)   NULL,
    [FromElementCondition]   VARCHAR (8000) NULL,
    [SourceXLSConditions]    VARCHAR (8000) NULL,
    [Formula Conversion]     VARCHAR (8000) NULL,
    [Column 9]               VARCHAR (8000) NULL,
    [Column 10]              VARCHAR (8000) NULL,
    [Column 11]              VARCHAR (8000) NULL,
    [Column 12]              VARCHAR (8000) NULL,
    [Column 13]              VARCHAR (8000) NULL,
    [Column 14]              VARCHAR (8000) NULL,
    [Column 15]              VARCHAR (8000) NULL,
    [Column 16]              VARCHAR (8000) NULL,
    [Column 17]              VARCHAR (8000) NULL,
    [Column 18]              VARCHAR (8000) NULL,
    [Column 19]              VARCHAR (8000) NULL,
    [Column 20]              VARCHAR (8000) NULL,
    [Column 21]              VARCHAR (8000) NULL,
    [Column 22]              VARCHAR (8000) NULL,
    [Column 23]              VARCHAR (8000) NULL,
    [Column 24]              VARCHAR (8000) NULL,
    [Column 25]              VARCHAR (8000) NULL,
    [Column 26]              VARCHAR (8000) NULL,
    [Column 27]              VARCHAR (8000) NULL
);

