CREATE TABLE [dbo].[EndState-RCSAdv] (
    [RCSADV_SEQ]            VARCHAR (200) NULL,
    [RCSADV_ADVERTISER]     VARCHAR (200) NULL,
    [RCSADV_CREATE_DTM]     VARCHAR (200) NULL,
    [RCSADV_EDIT_DTM]       VARCHAR (200) NULL,
    [RCSADV_CPTK_INST_CODE] VARCHAR (200) NULL,
    [RCSADV_CPTK_PRIORITY]  VARCHAR (200) NULL,
    [RCSADV_TV_PRIORITY]    VARCHAR (200) NULL
);

