CREATE TABLE [dbo].[EndState-SYNRates] (
    [CPSYN_SEQ]              VARCHAR (50) NULL,
    [CPSYN_PRGSYN_SEQ]       VARCHAR (50) NULL,
    [CPSYN_DISTRIBUTOR]      VARCHAR (50) NULL,
    [CPSYN_PROGRAM]          VARCHAR (50) NULL,
    [CPSYN_SQPRGSBCAT_SEQ]   VARCHAR (50) NULL,
    [CPSYN_BEGIN_DATE]       VARCHAR (50) NULL,
    [CPSYN_END_DATE]         VARCHAR (50) NULL,
    [CPSYN_CPP]              VARCHAR (50) NULL,
    [CPSYN_CREATE_DTM]       VARCHAR (50) NULL,
    [CPSYN_EDIT_DTM]         VARCHAR (50) NULL,
    [SQPRGSBCAT_CATEGORY]    VARCHAR (50) NULL,
    [SQPRGSBCAT_SUBCATEGORY] VARCHAR (50) NULL,
    [PRGSYN_SEQ]             VARCHAR (50) NULL,
    [PRGSYN_DISTRIBUTOR]     VARCHAR (50) NULL,
    [PRGSYN_PROGRAM]         VARCHAR (50) NULL,
    [PRGSYN_SQPRGSBCAT_SEQ]  VARCHAR (50) NULL,
    [PRGSYN_BEGIN_DATE]      VARCHAR (50) NULL,
    [PRGSYN_END_DATE]        VARCHAR (50) NULL,
    [PRGSYN_CREATE_DTM]      VARCHAR (50) NULL,
    [PRGSYN_EDIT_DTM]        VARCHAR (50) NULL
);

