CREATE TABLE [dbo].[EndState-Nodes] (
    [CLEARANCEMKTCODE] VARCHAR (50) NULL,
    [SERVER]           VARCHAR (50) NULL,
    [SOURCE]           VARCHAR (50) NULL,
    [CTLEGACYSEQ]      VARCHAR (50) NULL
);

