CREATE TABLE [dbo].[EndState-NetworkRates] (
    [CPNET_SEQ]              VARCHAR (50) NULL,
    [CPNET_NATLDPT_SEQ]      VARCHAR (50) NULL,
    [CPNET_NETWORK]          VARCHAR (50) NULL,
    [CPNET_SQPRGSBCAT_SEQ]   VARCHAR (50) NULL,
    [CPNET_BEGIN_DATE]       VARCHAR (50) NULL,
    [CPNET_END_DATE]         VARCHAR (50) NULL,
    [CPNET_CPP]              VARCHAR (50) NULL,
    [CPNET_CREATE_DTM]       VARCHAR (50) NULL,
    [CPNET_EDIT_DTM]         VARCHAR (50) NULL,
    [SQPRGSBCAT_CATEGORY]    VARCHAR (50) NULL,
    [SQPRGSBCAT_SUBCATEGORY] VARCHAR (50) NULL,
    [NATLDPT_SEQ]            VARCHAR (50) NULL,
    [NATLDPT_DAYPART]        VARCHAR (50) NULL,
    [NATLDPT_DAYS]           VARCHAR (50) NULL,
    [NATLDPT_START_TIME]     VARCHAR (50) NULL,
    [NATLDPT_END_TIME]       VARCHAR (50) NULL,
    [NATLDPT_CREATE_DTM]     VARCHAR (50) NULL,
    [NATLDPT_EDIT_DTM]       VARCHAR (50) NULL
);

