CREATE TABLE [dbo].[EndStateSQADPgmSubCat] (
    ["SQPRGSBCAT_SEQ"]         VARCHAR (50) NULL,
    ["SQPRGSBCAT_CATEGORY"]    VARCHAR (50) NULL,
    ["SQPRGSBCAT_SUBCATEGORY"] VARCHAR (50) NULL,
    ["SQPRGSBCAT_CREATE_DTM"]  VARCHAR (50) NULL,
    ["SQPRGSBCAT_EDIT_DTM"]    VARCHAR (50) NULL
);

