CREATE TABLE [dbo].[EndStateDayPartTimeZone] (
    [DPTZ_SEQ]        VARCHAR (50) NULL,
    [DPTZ_TIMEZONE]   VARCHAR (50) NULL,
    [DPTZ_DAY]        VARCHAR (50) NULL,
    [DPTZ_START_TIME] VARCHAR (50) NULL,
    [DPTZ_END_TIME]   VARCHAR (50) NULL,
    [DPTZ_DAYPART]    VARCHAR (50) NULL,
    [DPTZ_MODIFY_DTM] VARCHAR (50) NULL,
    [DPTZ_TVD_CODE]   VARCHAR (50) NULL
);

