CREATE TABLE [dbo].[EndState-RCSClass] (
    [RCSCLS_SEQ]                 VARCHAR (200) NULL,
    [RCSCLS_CLASS]               VARCHAR (200) NULL,
    [RCSCLS_CREATE_DTM]          VARCHAR (200) NULL,
    [RCSCLS_EDIT_DTM]            VARCHAR (200) NULL,
    [RCSCLS_CPTK_PRODCAT_CODE]   VARCHAR (200) NULL,
    [RCSCLS_CPTK_PRIORITY]       VARCHAR (200) NULL,
    [RCSCLS_REP_INITS]           VARCHAR (200) NULL,
    [RCSCLS_TV_PRIORITY]         VARCHAR (200) NULL,
    [RCSCLS_REP_NOTIFIED_DTM]    VARCHAR (200) NULL,
    [RCSCLS_TV_REP_INITS]        VARCHAR (200) NULL,
    [RCSCLS_TV_REP_NOTIFIED_DTM] VARCHAR (200) NULL,
    [RCSCLS_SP1]                 VARCHAR (200) NULL,
    [RCSCLS_HIS_SP1]             VARCHAR (200) NULL
);

