CREATE TABLE [dbo].[EndState-RefProduct2] (
    [PRCODE]  VARCHAR (100) NULL,
    [PRNAME]  VARCHAR (100) NULL,
    [PRINST]  VARCHAR (100) NULL,
    [PRICKE]  VARCHAR (100) NULL,
    [PRSBCAT] VARCHAR (100) NULL,
    [PRCATGY] VARCHAR (100) NULL,
    [PRMKT]   VARCHAR (100) NULL,
    [PRIGRP]  VARCHAR (100) NULL
);

