CREATE TABLE [dbo].[EndState-Publication] (
    [Cover Name]            VARCHAR (50)   NULL,
    [Pub Name]              VARCHAR (50)   NULL,
    [Market Name]           VARCHAR (50)   NULL,
    [Pub ID]                VARCHAR (50)   NULL,
    [Market ID]             VARCHAR (50)   NULL,
    [Legacy CT ID]          VARCHAR (50)   NULL,
    [Legacy CT Market]      VARCHAR (1000) NULL,
    [Legacy MT ID]          VARCHAR (50)   NULL,
    [Legacy MT Name]        VARCHAR (1000) NULL,
    [Legacy MT Market]      VARCHAR (1000) NULL,
    [Kim Comments]          VARCHAR (1000) NULL,
    [Legacy CT Name]        VARCHAR (1000) NULL,
    [Legacy CT ID2]         VARCHAR (50)   NULL,
    [Language]              VARCHAR (50)   NULL,
    [Ethnicity]             VARCHAR (50)   NULL,
    [Language ID]           VARCHAR (50)   NULL,
    [Ethnicity ID]          VARCHAR (50)   NULL,
    [Pub Type]              VARCHAR (50)   NULL,
    [Pub Universe]          VARCHAR (50)   NULL,
    [Pub Width]             VARCHAR (50)   NULL,
    [Pub Depth (Lines)]     VARCHAR (50)   NULL,
    [Pub Depth (Inches)]    VARCHAR (50)   NULL,
    [Pub Comments]          VARCHAR (50)   NULL,
    [End State Priority]    VARCHAR (50)   NULL,
    [Date Start]            VARCHAR (50)   NULL,
    [Date End]              VARCHAR (50)   NULL,
    [Brand (CT)]            VARCHAR (50)   NULL,
    [Promotion (MT)]        VARCHAR (50)   NULL,
    [Pub Validation ]       VARCHAR (50)   NULL,
    [Circ Queue ]           VARCHAR (50)   NULL,
    [Pub Queue]             VARCHAR (50)   NULL,
    [Multi Pub Market]      VARCHAR (50)   NULL,
    [Multi-Edition Pub]     VARCHAR (50)   NULL,
    [Recurrence Start Date] VARCHAR (50)   NULL,
    [Recurrence Days]       VARCHAR (50)   NULL,
    [Recurrence Frequency]  VARCHAR (50)   NULL,
    [Class]                 VARCHAR (50)   NULL,
    [ColumnInch]            VARCHAR (50)   NULL,
    [Display]               VARCHAR (50)   NULL,
    [ClassifiedLineage]     VARCHAR (50)   NULL,
    [Legacy Pubcat]         VARCHAR (50)   NULL,
    [Fast Track]            VARCHAR (50)   NULL,
    [Spend Universe]        VARCHAR (50)   NULL,
    [Column 43]             VARCHAR (50)   NULL,
    [Column 44]             VARCHAR (50)   NULL
);

