CREATE TABLE [dbo].[EndState-CableRates] (
    [CPCAB_SEQ]          VARCHAR (50) NULL,
    [CPCAB_NETWORK]      VARCHAR (50) NULL,
    [CPCAB_NATLDPT_SEQ]  VARCHAR (50) NULL,
    [CPCAB_BEGIN_DATE]   VARCHAR (50) NULL,
    [CPCAB_END_DATE]     VARCHAR (50) NULL,
    [CPCAB_CPP]          VARCHAR (50) NULL,
    [CPCAB_CREATE_DTM]   VARCHAR (50) NULL,
    [CPCAB_EDIT_DTM]     VARCHAR (50) NULL,
    [NATLDPT_SEQ]        VARCHAR (50) NULL,
    [NATLDPT_DAYPART]    VARCHAR (50) NULL,
    [NATLDPT_DAYS]       VARCHAR (50) NULL,
    [NATLDPT_START_TIME] VARCHAR (50) NULL,
    [NATLDPT_END_TIME]   VARCHAR (50) NULL,
    [NATLDPT_CREATE_DTM] VARCHAR (50) NULL,
    [NATLDPT_EDIT_DTM]   VARCHAR (50) NULL
);

