CREATE TABLE [dbo].[EndState-Advertisers] (
    [INSEQ]          VARCHAR (50) NULL,
    [INSTCOD]        VARCHAR (50) NULL,
    [INSTNAM]        VARCHAR (50) NULL,
    [INSTATE]        VARCHAR (50) NULL,
    [INCNTRY]        VARCHAR (50) NULL,
    [IN_RETIRE_DATE] VARCHAR (50) NULL,
    [INSHORTNAME]    VARCHAR (50) NULL,
    [IN_IGRPCOD]     VARCHAR (50) NULL,
    [INPARENT]       VARCHAR (50) NULL
);

