CREATE TABLE [dbo].[EndState-Sender-Kim] (
    [senderid]                     VARCHAR (50)   NULL,
    [Sender Name]                  VARCHAR (200)  NULL,
    [company]                      VARCHAR (200)  NULL,
    [contact name]                 VARCHAR (200)  NULL,
    [address]                      VARCHAR (200)  NULL,
    [address2]                     VARCHAR (200)  NULL,
    [city]                         VARCHAR (200)  NULL,
    [state]                        VARCHAR (200)  NULL,
    [zip code]                     VARCHAR (200)  NULL,
    [country]                      VARCHAR (50)   NULL,
    [billing mailing address]      VARCHAR (200)  NULL,
    [phone]                        VARCHAR (50)   NULL,
    [cell]                         VARCHAR (50)   NULL,
    [work]                         VARCHAR (50)   NULL,
    [other phone]                  VARCHAR (50)   NULL,
    [email]                        VARCHAR (200)  NULL,
    [start date]                   VARCHAR (50)   NULL,
    [end date]                     VARCHAR (50)   NULL,
    [priority]                     VARCHAR (50)   NULL,
    [frequency]                    VARCHAR (50)   NULL,
    [expected weekday]             VARCHAR (50)   NULL,
    [Type]                         VARCHAR (50)   NULL,
    [fex bulk label]               VARCHAR (50)   NULL,
    [has publications]             VARCHAR (50)   NULL,
    [sub payment]                  VARCHAR (50)   NULL,
    [special sending instructions] VARCHAR (1000) NULL,
    [cc notes]                     VARCHAR (1000) NULL,
    [comments]                     VARCHAR (1000) NULL,
    [early sender]                 VARCHAR (50)   NULL,
    [source id]                    VARCHAR (50)   NULL,
    [SIMR Indicator]               VARCHAR (50)   NULL,
    [Column 31]                    VARCHAR (50)   NULL
);

