CREATE TABLE [dbo].[EndState-Program] (
    [PGCODE]  VARCHAR (50) NULL,
    [PGNAME]  VARCHAR (50) NULL,
    [PGCHAN]  VARCHAR (50) NULL,
    [PGTYYPE] VARCHAR (50) NULL,
    [PGOTH]   VARCHAR (50) NULL,
    [PGTCODE] VARCHAR (50) NULL,
    [PG1]     VARCHAR (50) NULL,
    [PGSTADT] VARCHAR (50) NULL,
    [PGLRDT]  VARCHAR (50) NULL
);

