CREATE TABLE [dbo].[EndState-Expectation-Inserts] (
    [ExpectationId (Alan new)] VARCHAR (500) NULL,
    [ExpectationID (old)]      VARCHAR (500) NULL,
    [Advertiser]               VARCHAR (500) NULL,
    [Mkt]                      VARCHAR (500) NULL,
    [Country of Origin (new)]  VARCHAR (500) NULL,
    [Media Type]               VARCHAR (500) NULL,
    [Kim Comment]              VARCHAR (500) NULL,
    [RetId]                    VARCHAR (500) NULL,
    [MktId]                    VARCHAR (500) NULL,
    [MediaId]                  VARCHAR (500) NULL,
    [Priority]                 VARCHAR (500) NULL,
    [FrequencyId]              VARCHAR (500) NULL,
    [StartDt]                  VARCHAR (500) NULL,
    [EndDt]                    VARCHAR (500) NULL,
    [Media Comments]           VARCHAR (500) NULL,
    [MissingAdComments]        VARCHAR (500) NULL,
    [ScanDPI]                  VARCHAR (500) NULL,
    [rowguid]                  VARCHAR (500) NULL,
    [Brand (CT)]               VARCHAR (500) NULL,
    [AdDynReqInd]              VARCHAR (500) NULL,
    [AdSmtReqInd]              VARCHAR (500) NULL,
    [ScanReqInd]               VARCHAR (500) NULL,
    [jaAlcInd]                 VARCHAR (500) NULL,
    [jaAlcMInd]                VARCHAR (500) NULL,
    [jaAlcVInd]                VARCHAR (500) NULL,
    [jaallInd]                 VARCHAR (500) NULL,
    [jaAllmInd]                VARCHAR (500) NULL,
    [jaAllvInd]                VARCHAR (500) NULL,
    [jaasmInd]                 VARCHAR (500) NULL,
    [jabevInd]                 VARCHAR (500) NULL,
    [jacanInd]                 VARCHAR (500) NULL,
    [jafrVInd]                 VARCHAR (500) NULL,
    [jaHSPeInd]                VARCHAR (500) NULL,
    [jaHSPsInd]                VARCHAR (500) NULL,
    [jalnetInd]                VARCHAR (500) NULL,
    [jamassInd]                VARCHAR (500) NULL,
    [jaspanInd]                VARCHAR (500) NULL,
    [email]                    VARCHAR (500) NULL,
    [ROPPageNameInd]           VARCHAR (500) NULL,
    [FVEntry360Ind]            VARCHAR (500) NULL,
    [IndAutoQC]                VARCHAR (500) NULL
);

