CREATE TABLE [dbo].[EndStateSchedule] (
    [NYS_CPTK_CODE]  VARCHAR (50) NULL,
    [NYS_CHANNEL]    VARCHAR (50) NULL,
    [PGCHAN]         VARCHAR (50) NULL,
    [NYS_AIR_DATE]   VARCHAR (50) NULL,
    [NYS_START_TIME] VARCHAR (50) NULL,
    [NYS_END_TIME]   VARCHAR (50) NULL
);

