CREATE TABLE [dbo].[ExpectationLog] (
    [LogTimeStamp]                 DATETIME      NULL,
    [LogDMLOperation]              CHAR (1)      NULL,
    [LoginUser]                    VARCHAR (32)  NULL,
    [ExpectationID]                INT           NULL,
    [RetailerID]                   INT           NULL,
    [OldVal_RetailerID]            INT           NULL,
    [MarketID]                     INT           NULL,
    [OldVal_MarketID]              INT           NULL,
    [MediaID]                      INT           NULL,
    [OldVal_MediaID]               INT           NULL,
    [FrequencyID]                  INT           NULL,
    [OldVal_FrequencyID]           INT           NULL,
    [StartDT]                      DATETIME      NULL,
    [OldVal_StartDT]               DATETIME      NULL,
    [EndDT]                        DATETIME      NULL,
    [OldVal_EndDT]                 DATETIME      NULL,
    [Priority]                     INT           NULL,
    [OldVal_Priority]              INT           NULL,
    [Comments]                     VARCHAR (250) NULL,
    [OldVal_Comments]              VARCHAR (250) NULL,
    [FVReqInd]                     TINYINT       NULL,
    [OldVal_FVReqInd]              TINYINT       NULL,
    [ADReqInd]                     TINYINT       NULL,
    [OldVal_ADReqInd]              TINYINT       NULL,
    [MissingAdComments]            VARCHAR (250) NULL,
    [OldVal_MissingAdComments]     VARCHAR (250) NULL,
    [ScanDPI]                      INT           NULL,
    [OldVal_ScanDPI]               INT           NULL,
    [AdDynReqInd]                  TINYINT       NULL,
    [OldVal_AdDynReqInd]           TINYINT       NULL,
    [AdSmtReqInd]                  TINYINT       NULL,
    [OldVal_AdSmtReqInd]           TINYINT       NULL,
    [ScanReqInd]                   TINYINT       NULL,
    [OldVal_ScanReqInd]            TINYINT       NULL,
    [FsiInd]                       TINYINT       NULL,
    [OldVal_FsiInd]                TINYINT       NULL,
    [JaAlcInd]                     TINYINT       NULL,
    [OldVal_JaAlcInd]              TINYINT       NULL,
    [JaAlcMInd]                    TINYINT       NULL,
    [OldVal_JaAlcMInd]             TINYINT       NULL,
    [JaAlcVInd]                    TINYINT       NULL,
    [OldVal_JaAlcVInd]             TINYINT       NULL,
    [JaallInd]                     TINYINT       NULL,
    [OldVal_JaallInd]              TINYINT       NULL,
    [JaAllmInd]                    TINYINT       NULL,
    [OldVal_JaAllmInd]             TINYINT       NULL,
    [JaAllvInd]                    TINYINT       NULL,
    [OldVal_JaAllvInd]             TINYINT       NULL,
    [JaasmInd]                     TINYINT       NULL,
    [OldVal_JaasmInd]              TINYINT       NULL,
    [JabevInd]                     TINYINT       NULL,
    [OldVal_JabevInd]              TINYINT       NULL,
    [JacanInd]                     TINYINT       NULL,
    [OldVal_JacanInd]              TINYINT       NULL,
    [JafrVInd]                     TINYINT       NULL,
    [OldVal_JafrVInd]              TINYINT       NULL,
    [JaHSPeInd]                    TINYINT       NULL,
    [OldVal_JaHSPeInd]             TINYINT       NULL,
    [JaHSPsInd]                    TINYINT       NULL,
    [OldVal_JaHSPsInd]             TINYINT       NULL,
    [JalnetInd]                    TINYINT       NULL,
    [OldVal_JalnetInd]             TINYINT       NULL,
    [JamassInd]                    TINYINT       NULL,
    [OldVal_JamassInd]             TINYINT       NULL,
    [JaspanInd]                    TINYINT       NULL,
    [OldVal_JaspanInd]             TINYINT       NULL,
    [Email]                        TINYINT       NULL,
    [OldVal_Email]                 TINYINT       NULL,
    [ROPPageNameInd]               TINYINT       NULL,
    [OldVal_ROPPageNameInd]        TINYINT       NULL,
    [FVEntry360Ind]                TINYINT       NULL,
    [OldVal_FVEntry360Ind]         TINYINT       NULL,
    [ADEntry360Ind]                TINYINT       NULL,
    [OldVal_ADEntry360Ind]         TINYINT       NULL,
    [IndAutoQC]                    TINYINT       NULL,
    [OldVal_IndAutoQC]             TINYINT       NULL,
    [AdvertiserID]                 INT           NULL,
    [OldVal_AdvertiserID]          INT           NULL,
    [PromotionAdLevel]             INT           NULL,
    [OldVal_PromotionAdLevel]      INT           NULL,
    [PromotionConsumable]          INT           NULL,
    [OldVal_PromotionConsumable]   INT           NULL,
    [PromotionDurables]            INT           NULL,
    [OldVal_PromotionDurables]     INT           NULL,
    [Brand]                        INT           NULL,
    [OldVal_Brand]                 INT           NULL,
    [AdComparison]                 INT           NULL,
    [OldVal_AdComparison]          INT           NULL,
    [CountryOfOrigin]              VARCHAR (50)  NULL,
    [OldVal_CountryOfOrigin]       VARCHAR (50)  NULL,
    [MTLegacyExpectationID]        INT           NULL,
    [OldVal_MTLegacyExpectationID] INT           NULL,
    CHECK ([LogDMLOperation]='U' OR [LogDMLOperation]='I' OR [LogDMLOperation]='D')
);

