CREATE TABLE [dbo].[ExpectationBackup20160314] (
    [ExpectationID]     INT           NOT NULL,
    [RetailerID]        INT           NULL,
    [MarketID]          INT           NULL,
    [MediaID]           INT           NULL,
    [FrequencyID]       INT           NULL,
    [StartDT]           DATETIME      NULL,
    [EndDT]             DATETIME      NULL,
    [Priority]          INT           NULL,
    [Comments]          VARCHAR (250) NULL,
    [FVReqInd]          TINYINT       NULL,
    [ADReqInd]          TINYINT       NULL,
    [MissingAdComments] VARCHAR (250) NULL,
    [ScanDPI]           INT           NULL,
    [AdDynReqInd]       TINYINT       NULL,
    [AdSmtReqInd]       TINYINT       NULL,
    [ScanReqInd]        TINYINT       NULL,
    [FsiInd]            TINYINT       NULL,
    [JaAlcInd]          TINYINT       NULL,
    [JaAlcMInd]         TINYINT       NULL,
    [JaAlcVInd]         TINYINT       NULL,
    [JaallInd]          TINYINT       NULL,
    [JaAllmInd]         TINYINT       NULL,
    [JaAllvInd]         TINYINT       NULL,
    [JaasmInd]          TINYINT       NULL,
    [JabevInd]          TINYINT       NULL,
    [JacanInd]          TINYINT       NULL,
    [JafrVInd]          TINYINT       NULL,
    [JaHSPeInd]         TINYINT       NULL,
    [JaHSPsInd]         TINYINT       NULL,
    [JalnetInd]         TINYINT       NULL,
    [JamassInd]         TINYINT       NULL,
    [JaspanInd]         TINYINT       NULL,
    [Email]             TINYINT       NULL,
    [ROPPageNameInd]    TINYINT       NULL,
    [FVEntry360Ind]     TINYINT       NULL,
    [ADEntry360Ind]     TINYINT       NULL,
    [IndAutoQC]         TINYINT       NULL
);

