CREATE TABLE [dbo].[Market20161117] (
    [MarketID]                      INT            IDENTITY (1, 1) NOT NULL,
    [Descrip]                       VARCHAR (50)   NULL,
    [StartDT]                       DATETIME       NULL,
    [EndDT]                         DATETIME       NULL,
    [RegionID]                      INT            NULL,
    [TVOccurrenceThreshold]         INT            NULL,
    [Abbrevation]                   VARCHAR (50)   NULL,
    [State]                         VARCHAR (10)   NULL,
    [Region]                        VARCHAR (10)   NULL,
    [Country]                       VARCHAR (10)   NULL,
    [NielsenDMAName]                VARCHAR (50)   NULL,
    [CreatedDT]                     DATETIME       NULL,
    [CreatedByID]                   INT            NULL,
    [ModifiedDT]                    DATETIME       NULL,
    [ModifiedByID]                  INT            NULL,
    [CTLegacyLMKTCODE]              VARCHAR (10)   NULL,
    [CTLegacyLPERCENT]              NUMERIC (5, 4) NULL,
    [CTLegacyLTYPECODE]             VARCHAR (10)   NULL,
    [CTLegacyLWSJREG]               VARCHAR (10)   NULL,
    [MTLegacyMktID]                 INT            NULL,
    [MTLegacyRegionID]              INT            NULL,
    [MTLegacyRegionDescrip]         VARCHAR (100)  NULL,
    [MTLegacyAdamsEmailTrainingInd] VARCHAR (3)    NULL,
    [DisplayInMediaStreams]         INT            NULL,
    [Promotion]                     VARCHAR (50)   NULL,
    [Brand]                         VARCHAR (50)   NULL
);

