CREATE TABLE [dbo].[MarketLog] (
    [LogTimeStamp]                         DATETIME       NULL,
    [LogDMLOperation]                      CHAR (1)       NULL,
    [LoginUser]                            VARCHAR (32)   NULL,
    [MarketID]                             INT            NULL,
    [Descrip]                              VARCHAR (50)   NULL,
    [OldVal_Descrip]                       VARCHAR (50)   NULL,
    [StartDT]                              DATETIME       NULL,
    [OldVal_StartDT]                       DATETIME       NULL,
    [EndDT]                                DATETIME       NULL,
    [OldVal_EndDT]                         DATETIME       NULL,
    [RegionID]                             INT            NULL,
    [OldVal_RegionID]                      INT            NULL,
    [TVOccurrenceThreshold]                INT            NULL,
    [OldVal_TVOccurrenceThreshold]         INT            NULL,
    [Abbrevation]                          VARCHAR (50)   NULL,
    [OldVal_Abbrevation]                   VARCHAR (50)   NULL,
    [State]                                VARCHAR (10)   NULL,
    [OldVal_State]                         VARCHAR (10)   NULL,
    [Region]                               VARCHAR (10)   NULL,
    [OldVal_Region]                        VARCHAR (10)   NULL,
    [Country]                              VARCHAR (10)   NULL,
    [OldVal_Country]                       VARCHAR (10)   NULL,
    [NielsenDMAName]                       VARCHAR (50)   NULL,
    [OldVal_NielsenDMAName]                VARCHAR (50)   NULL,
    [CreatedDT]                            DATETIME       NULL,
    [OldVal_CreatedDT]                     DATETIME       NULL,
    [CreatedByID]                          INT            NULL,
    [OldVal_CreatedByID]                   INT            NULL,
    [ModifiedDT]                           DATETIME       NULL,
    [OldVal_ModifiedDT]                    DATETIME       NULL,
    [ModifiedByID]                         INT            NULL,
    [OldVal_ModifiedByID]                  INT            NULL,
    [CTLegacyLMKTCODE]                     VARCHAR (10)   NULL,
    [OldVal_CTLegacyLMKTCODE]              VARCHAR (10)   NULL,
    [CTLegacyLPERCENT]                     NUMERIC (5, 4) NULL,
    [OldVal_CTLegacyLPERCENT]              NUMERIC (5, 4) NULL,
    [CTLegacyLTYPECODE]                    VARCHAR (10)   NULL,
    [OldVal_CTLegacyLTYPECODE]             VARCHAR (10)   NULL,
    [CTLegacyLWSJREG]                      VARCHAR (10)   NULL,
    [OldVal_CTLegacyLWSJREG]               VARCHAR (10)   NULL,
    [MTLegacyMktID]                        INT            NULL,
    [OldVal_MTLegacyMktID]                 INT            NULL,
    [MTLegacyRegionID]                     INT            NULL,
    [OldVal_MTLegacyRegionID]              INT            NULL,
    [MTLegacyRegionDescrip]                VARCHAR (100)  NULL,
    [OldVal_MTLegacyRegionDescrip]         VARCHAR (100)  NULL,
    [MTLegacyAdamsEmailTrainingInd]        VARCHAR (3)    NULL,
    [OldVal_MTLegacyAdamsEmailTrainingInd] VARCHAR (3)    NULL,
    [DisplayInMediaStreams]                INT            NULL,
    [OldVal_DisplayInMediaStreams]         INT            NULL,
    [Promotion]                            VARCHAR (50)   NULL,
    [OldVal_Promotion]                     VARCHAR (50)   NULL,
    [Brand]                                VARCHAR (50)   NULL,
    [OldVal_Brand]                         VARCHAR (50)   NULL,
    CHECK ([LogDMLOperation]='U' OR [LogDMLOperation]='I' OR [LogDMLOperation]='D')
);

