CREATE TABLE [dbo].[MediaTypeLog] (
    [LogTimeStamp]                DATETIME      NULL,
    [LogDMLOperation]             CHAR (1)      NULL,
    [LoginUser]                   VARCHAR (32)  NULL,
    [MediaTypeID]                 INT           NULL,
    [Descrip]                     VARCHAR (50)  NULL,
    [OldVal_Descrip]              VARCHAR (50)  NULL,
    [MediaStream]                 VARCHAR (50)  NULL,
    [OldVal_MediaStream]          VARCHAR (50)  NULL,
    [IndDisplayValue]             TINYINT       NULL,
    [OldVal_IndDisplayValue]      TINYINT       NULL,
    [IndIgnorePublication]        TINYINT       NULL,
    [OldVal_IndIgnorePublication] TINYINT       NULL,
    [IndTreatasFSI]               TINYINT       NULL,
    [OldVal_IndTreatasFSI]        TINYINT       NULL,
    [DisplayDescrip]              VARCHAR (50)  NULL,
    [OldVal_DisplayDescrip]       VARCHAR (50)  NULL,
    [DefaultPubID]                INT           NULL,
    [OldVal_DefaultPubID]         INT           NULL,
    [DefaultSizeMethod]           VARCHAR (MAX) NULL,
    [OldVal_DefaultSizeMethod]    VARCHAR (MAX) NULL,
    [ActiveInd]                   INT           NULL,
    [OldVal_ActiveInd]            INT           NULL,
    [CreateDTM]                   DATETIME      NULL,
    [OldVal_CreateDTM]            DATETIME      NULL,
    [CreateBy]                    INT           NULL,
    [OldVal_CreateBy]             INT           NULL,
    [ModifiedDT]                  DATETIME      NULL,
    [OldVal_ModifiedDT]           DATETIME      NULL,
    [ModifiedByID]                INT           NULL,
    [OldVal_ModifiedByID]         INT           NULL,
    [MTLegacyMediaID]             INT           NULL,
    [OldVal_MTLegacyMediaID]      INT           NULL,
    CHECK ([LogDMLOperation]='U' OR [LogDMLOperation]='I' OR [LogDMLOperation]='D')
);

