CREATE TABLE [dbo].[NLSNSpotRating] (
    [NLSNSpotRatingID] INT          IDENTITY (1, 1) NOT NULL,
    [TVStationID]      VARCHAR (50) NOT NULL,
    [AirDate]          DATE         NOT NULL,
    [StartTime]        TIME (7)     NOT NULL,
    [EndTime]          TIME (7)     NOT NULL,
    [HouseHold]        BIGINT       NULL,
    [c2_5]             BIGINT       NULL,
    [c6_11]            BIGINT       NULL,
    [m12_14]           BIGINT       NULL,
    [m15_17]           BIGINT       NULL,
    [m18_20]           BIGINT       NULL,
    [m21_24]           BIGINT       NULL,
    [m25_34]           BIGINT       NULL,
    [m35_49]           BIGINT       NULL,
    [m50_54]           BIGINT       NULL,
    [m55_64]           BIGINT       NULL,
    [m65P]             BIGINT       NULL,
    [f12_14]           BIGINT       NULL,
    [f15_17]           BIGINT       NULL,
    [f18_20]           BIGINT       NULL,
    [f21_24]           BIGINT       NULL,
    [f25_34]           BIGINT       NULL,
    [f35_49]           BIGINT       NULL,
    [f50_54]           BIGINT       NULL,
    [f55_64]           BIGINT       NULL,
    [f65P]             BIGINT       NULL,
    CONSTRAINT [PK_NLSNSpotRating] PRIMARY KEY CLUSTERED ([NLSNSpotRatingID] ASC)
);

