CREATE TABLE [dbo].[NLSNStationAndMarketMapBA] (
    [MKTMAP_UNIV]      VARCHAR (255) NULL,
    [MKTMAP_NIS_MKT]   FLOAT (53)    NULL,
    [MKTMAP_CPTK_MKT]  VARCHAR (255) NULL,
    [MKTMAP_NIS_STAT]  VARCHAR (255) NULL,
    [MKTMAP_CPTK_STAT] VARCHAR (255) NULL,
    [MKTMAP_TAKE]      VARCHAR (255) NULL
);

