CREATE TABLE [dbo].[OccurrenceDetailEMLogStaging] (
    [LogTimeStamp]                    DATETIME      NULL,
    [LogDMLOperation]                 CHAR (1)      NULL,
    [LoginUser]                       VARCHAR (32)  NULL,
    [OccurrenceDetailEMID]            INT           NULL,
    [AdvertiserID]                    INT           NULL,
    [OldVal_AdvertiserID]             INT           NULL,
    [MediaTypeID]                     INT           NULL,
    [OldVal_MediaTypeID]              INT           NULL,
    [MarketID]                        INT           NULL,
    [OldVal_MarketID]                 INT           NULL,
    [AdvertiserEmailID]               INT           NULL,
    [OldVal_AdvertiserEmailID]        INT           NULL,
    [SenderPersonaID]                 INT           NULL,
    [OldVal_SenderPersonaID]          INT           NULL,
    [ParentOccurrenceID]              INT           NULL,
    [OldVal_ParentOccurrenceID]       INT           NULL,
    [EnvelopeID]                      INT           NULL,
    [OldVal_EnvelopeID]               INT           NULL,
    [AdID]                            INT           NULL,
    [OldVal_AdID]                     INT           NULL,
    [PatternID]                       INT           NULL,
    [OldVal_PatternID]                INT           NULL,
    [DistributionDT]                  DATE          NULL,
    [OldVal_DistributionDT]           DATE          NULL,
    [AdDT]                            DATE          NULL,
    [OldVal_AdDT]                     DATE          NULL,
    [Priority]                        INT           NULL,
    [OldVal_Priority]                 INT           NULL,
    [SubjectLine]                     VARCHAR (200) NULL,
    [OldVal_SubjectLine]              VARCHAR (200) NULL,
    [LandingPageID]                   INT           NULL,
    [OldVal_LandingPageID]            INT           NULL,
    [PromotionalInd]                  TINYINT       NULL,
    [OldVal_PromotionalInd]           TINYINT       NULL,
    [AssignedtoOffice]                VARCHAR (200) NULL,
    [OldVal_AssignedtoOffice]         VARCHAR (200) NULL,
    [NoTakeReason]                    VARCHAR (200) NULL,
    [OldVal_NoTakeReason]             VARCHAR (200) NULL,
    [Query]                           TINYINT       NULL,
    [OldVal_Query]                    TINYINT       NULL,
    [MapStatusID]                     INT           NULL,
    [OldVal_MapStatusID]              INT           NULL,
    [IndexStatusID]                   INT           NULL,
    [OldVal_IndexStatusID]            INT           NULL,
    [ScanStatusID]                    INT           NULL,
    [OldVal_ScanStatusID]             INT           NULL,
    [QCStatusID]                      INT           NULL,
    [OldVal_QCStatusID]               INT           NULL,
    [RouteStatusID]                   INT           NULL,
    [OldVal_RouteStatusID]            INT           NULL,
    [OccurrenceStatusID]              INT           NULL,
    [OldVal_OccurrenceStatusID]       INT           NULL,
    [CreateFromAuditIndicator]        TINYINT       NULL,
    [OldVal_CreateFromAuditIndicator] TINYINT       NULL,
    [FlyerID]                         INT           NULL,
    [OldVal_FlyerID]                  INT           NULL,
    [AuditedByID]                     INT           NULL,
    [OldVal_AuditedByID]              INT           NULL,
    [AuditedDT]                       DATETIME      NULL,
    [OldVal_AuditedDT]                DATETIME      NULL,
    [CreatedDT]                       DATETIME      NULL,
    [OldVal_CreatedDT]                DATETIME      NULL,
    [CreatedByID]                     INT           NULL,
    [OldVal_CreatedByID]              INT           NULL,
    [ModifiedDT]                      DATETIME      NULL,
    [OldVal_ModifiedDT]               DATETIME      NULL,
    [ModifiedByID]                    INT           NULL,
    [OldVal_ModifiedByID]             INT           NULL,
    [CTLegacySeq]                     INT           NULL,
    [OldVal_CTLegacySeq]              INT           NULL
);

