CREATE TABLE [dbo].[OccurrenceClientFacingTVLog] (
    [LogTimeStamp]                   DATETIME     NULL,
    [LogDMLOperation]                CHAR (1)     NULL,
    [LoginUser]                      VARCHAR (32) NULL,
    [OccurrenceClientFacingTVId]     INT          NULL,
    [OccurrenceDetailTVId]           INT          NULL,
    [OldVal_OccurrenceDetailTVId]    INT          NULL,
    [AdID]                           INT          NULL,
    [OldVal_AdID]                    INT          NULL,
    [OccurrenceClearanceTVId]        INT          NULL,
    [OldVal_OccurrenceClearanceTVId] INT          NULL,
    [ProgramFormatMasterId]          INT          NULL,
    [OldVal_ProgramFormatMasterId]   INT          NULL,
    [Valid]                          BIT          NULL,
    [OldVal_Valid]                   BIT          NULL,
    [AirDate]                        DATETIME     NULL,
    [OldVal_AirDate]                 DATETIME     NULL,
    [AirStartTime]                   DATETIME     NULL,
    [OldVal_AirStartTime]            DATETIME     NULL,
    [AirEndTime]                     DATETIME     NULL,
    [OldVal_AirEndTime]              DATETIME     NULL,
    [CreatedDT]                      DATETIME     NULL,
    [OldVal_CreatedDT]               DATETIME     NULL,
    [CreatedByID]                    INT          NULL,
    [OldVal_CreatedByID]             INT          NULL,
    [ModifiedDT]                     DATETIME     NULL,
    [OldVal_ModifiedDT]              DATETIME     NULL,
    [ModifiedByID]                   INT          NULL,
    [OldVal_ModifiedByID]            INT          NULL,
    [TVNationalClearanceID]          INT          NULL,
    [OldVal_TVNationalClearanceID]   INT          NULL,
    [TVStationID]                    INT          NULL,
    [OldVal_TVStationID]             INT          NULL,
    [Clearance]                      VARCHAR (50) NULL,
    [OldVal_Clearance]               VARCHAR (50) NULL,
    [ClearanceMethod]                VARCHAR (50) NULL,
    [OldVal_ClearanceMethod]         VARCHAR (50) NULL,
    [ProgramID]                      INT          NULL,
    [OldVal_ProgramID]               INT          NULL,
    [EpisodeID]                      VARCHAR (50) NULL,
    [OldVal_EpisodeID]               VARCHAR (50) NULL,
    CHECK ([LogDMLOperation]='U' OR [LogDMLOperation]='I' OR [LogDMLOperation]='D')
);

