CREATE TABLE [dbo].[OccurrenceDetailONVLog] (
    [LogTimeStamp]             DATETIME     NULL,
    [LogDMLOperation]          CHAR (1)     NULL,
    [LoginUser]                VARCHAR (32) NULL,
    [OccurrenceDetailONVID]    INT          NULL,
    [PatternStagingID]         INT          NULL,
    [OldVal_PatternStagingID]  INT          NULL,
    [PatternID]                INT          NULL,
    [OldVal_PatternID]         INT          NULL,
    [ScrapeSessionID]          INT          NULL,
    [OldVal_ScrapeSessionID]   INT          NULL,
    [ScrapePageID]             INT          NULL,
    [OldVal_ScrapePageID]      INT          NULL,
    [LandingPageID]            INT          NULL,
    [OldVal_LandingPageID]     INT          NULL,
    [AdID]                     INT          NULL,
    [OldVal_AdID]              INT          NULL,
    [ResultID]                 BIGINT       NULL,
    [OldVal_ResultID]          BIGINT       NULL,
    [OccurrenceDT]             DATETIME     NULL,
    [OldVal_OccurrenceDT]      DATETIME     NULL,
    [CreatedDT]                DATETIME     NULL,
    [OldVal_CreatedDT]         DATETIME     NULL,
    [ModifiedDT]               DATETIME     NULL,
    [OldVal_ModifiedDT]        DATETIME     NULL,
    [CreativeSignature]        VARCHAR (50) NULL,
    [OldVal_CreativeSignature] VARCHAR (50) NULL,
    [CTLegacySeq]              INT          NULL,
    [OldVal_CTLegacySeq]       INT          NULL,
    CHECK ([LogDMLOperation]='U' OR [LogDMLOperation]='I' OR [LogDMLOperation]='D')
);

