CREATE TABLE [dbo].[OccurrenceDetailODRLogStaging_XXX] (
    [LogTimeStamp]            DATETIME      NULL,
    [LogDMLOperation]         CHAR (1)      NULL,
    [LoginUser]               VARCHAR (32)  NULL,
    [OccurrenceDetailODRID]   BIGINT        NULL,
    [PatternID]               INT           NULL,
    [OldVal_PatternID]        INT           NULL,
    [AdID]                    INT           NULL,
    [OldVal_AdID]             INT           NULL,
    [MTMarketID]              INT           NULL,
    [OldVal_MTMarketID]       INT           NULL,
    [AdFormatID]              INT           NULL,
    [OldVal_AdFormatID]       INT           NULL,
    [ImageFileName]           VARCHAR (200) NULL,
    [OldVal_ImageFileName]    VARCHAR (200) NULL,
    [Priority]                INT           NULL,
    [OldVal_Priority]         INT           NULL,
    [SourceFTPFolder]         VARCHAR (200) NULL,
    [OldVal_SourceFTPFolder]  VARCHAR (200) NULL,
    [CMSImageDT]              DATETIME      NULL,
    [OldVal_CMSImageDT]       DATETIME      NULL,
    [CMSImageSize]            INT           NULL,
    [OldVal_CMSImageSize]     INT           NULL,
    [MTImageDT]               DATETIME      NULL,
    [OldVal_MTImageDT]        DATETIME      NULL,
    [MTImageSize]             INT           NULL,
    [OldVal_MTImageSize]      INT           NULL,
    [Advertiser]              VARCHAR (200) NULL,
    [OldVal_Advertiser]       VARCHAR (200) NULL,
    [DisplayLocation]         VARCHAR (200) NULL,
    [OldVal_DisplayLocation]  VARCHAR (200) NULL,
    [DatePictureTaken]        DATETIME      NULL,
    [OldVal_DatePictureTaken] DATETIME      NULL,
    [Errors]                  VARCHAR (200) NULL,
    [OldVal_Errors]           VARCHAR (200) NULL,
    [CorrectedName]           VARCHAR (200) NULL,
    [OldVal_CorrectedName]    VARCHAR (200) NULL,
    [FileSource]              VARCHAR (200) NULL,
    [OldVal_FileSource]       VARCHAR (200) NULL,
    [FileSourceType]          VARCHAR (200) NULL,
    [OldVal_FileSourceType]   VARCHAR (200) NULL,
    [WorkType]                INT           NULL,
    [OldVal_WorkType]         INT           NULL,
    [CreatedDT]               DATETIME      NULL,
    [OldVal_CreatedDT]        DATETIME      NULL,
    [ModifiedDT]              DATETIME      NULL,
    [OldVal_ModifiedDT]       DATETIME      NULL
);

