CREATE TABLE [dbo].[OccurrenceClientFacingRALog] (
    [LogTimeStamp]                   DATETIME     NULL,
    [LogDMLOperation]                CHAR (1)     NULL,
    [LoginUser]                      VARCHAR (32) NULL,
    [OccurrenceClientFacingRAId]     INT          NULL,
    [OccurrenceDetailRAId]           INT          NULL,
    [OldVal_OccurrenceDetailRAId]    INT          NULL,
    [AdID]                           INT          NULL,
    [OldVal_AdID]                    INT          NULL,
    [OccurrenceClearanceRAId]        INT          NULL,
    [OldVal_OccurrenceClearanceRAId] INT          NULL,
    [ProgramFormatMasterId]          INT          NULL,
    [OldVal_ProgramFormatMasterId]   INT          NULL,
    [Valid]                          BIT          NULL,
    [OldVal_Valid]                   BIT          NULL,
    [AirDate]                        DATETIME     NULL,
    [OldVal_AirDate]                 DATETIME     NULL,
    [AirStartTime]                   DATETIME     NULL,
    [OldVal_AirStartTime]            DATETIME     NULL,
    [AirEndTime]                     DATETIME     NULL,
    [OldVal_AirEndTime]              DATETIME     NULL,
    [CreateDTM]                      DATETIME     NULL,
    [OldVal_CreateDTM]               DATETIME     NULL,
    [CreateBy]                       INT          NULL,
    [OldVal_CreateBy]                INT          NULL,
    [ModifiedDTM]                    DATETIME     NULL,
    [OldVal_ModifiedDTM]             DATETIME     NULL,
    [ModifiedBy]                     INT          NULL,
    [OldVal_ModifiedBy]              INT          NULL,
    CHECK ([LogDMLOperation]='U' OR [LogDMLOperation]='I' OR [LogDMLOperation]='D')
);

