CREATE TABLE [dbo].[OccurrenceDetailMOBLog] (
    [LogTimeStamp]             DATETIME     NULL,
    [LogDMLOperation]          CHAR (1)     NULL,
    [LoginUser]                VARCHAR (32) NULL,
    [OccurrenceDetailMOBID]    INT          NULL,
    [PatternStagingID]         INT          NULL,
    [OldVal_PatternStagingID]  INT          NULL,
    [PatternID]                INT          NULL,
    [OldVal_PatternID]         INT          NULL,
    [CaptureSessionID]         INT          NULL,
    [OldVal_CaptureSessionID]  INT          NULL,
    [ScrapePageID]             INT          NULL,
    [OldVal_ScrapePageID]      INT          NULL,
    [LandingPageID]            INT          NULL,
    [OldVal_LandingPageID]     INT          NULL,
    [AdID]                     INT          NULL,
    [OldVal_AdID]              INT          NULL,
    [ResultID]                 BIGINT       NULL,
    [OldVal_ResultID]          BIGINT       NULL,
    [OccurrenceDT]             DATETIME     NULL,
    [OldVal_OccurrenceDT]      DATETIME     NULL,
    [AdType]                   INT          NULL,
    [OldVal_AdType]            INT          NULL,
    [LandingPageType]          INT          NULL,
    [OldVal_LandingPageType]   INT          NULL,
    [NumLandingPages]          INT          NULL,
    [OldVal_NumLandingPages]   INT          NULL,
    [CreatedDT]                DATETIME     NULL,
    [OldVal_CreatedDT]         DATETIME     NULL,
    [ModifiedDT]               DATETIME     NULL,
    [OldVal_ModifiedDT]        DATETIME     NULL,
    [CreativeSignature]        VARCHAR (50) NULL,
    [OldVal_CreativeSignature] VARCHAR (50) NULL,
    [OldPatternID]             INT          NULL,
    [OldVal_OldPatternID]      INT          NULL,
    CHECK ([LogDMLOperation]='U' OR [LogDMLOperation]='I' OR [LogDMLOperation]='D')
);

