CREATE TABLE [dbo].[OccurrenceDetailCIRLog] (
    [LogTimeStamp]                    DATETIME      NULL,
    [LogDMLOperation]                 CHAR (1)      NULL,
    [LoginUser]                       VARCHAR (32)  NULL,
    [OccurrenceDetailCIRID]           BIGINT        NULL,
    [AdID]                            INT           NULL,
    [OldVal_AdID]                     INT           NULL,
    [AdvertiserID]                    INT           NULL,
    [OldVal_AdvertiserID]             INT           NULL,
    [MediaTypeID]                     INT           NULL,
    [OldVal_MediaTypeID]              INT           NULL,
    [MarketID]                        INT           NULL,
    [OldVal_MarketID]                 INT           NULL,
    [PubEditionID]                    INT           NULL,
    [OldVal_PubEditionID]             INT           NULL,
    [LanguageID]                      INT           NULL,
    [OldVal_LanguageID]               INT           NULL,
    [EnvelopeID]                      INT           NULL,
    [OldVal_EnvelopeID]               INT           NULL,
    [PatternID]                       INT           NULL,
    [OldVal_PatternID]                INT           NULL,
    [SubSourceID]                     INT           NULL,
    [OldVal_SubSourceID]              INT           NULL,
    [DistributionDate]                DATE          NULL,
    [OldVal_DistributionDate]         DATE          NULL,
    [AdDate]                          DATE          NULL,
    [OldVal_AdDate]                   DATE          NULL,
    [Priority]                        INT           NULL,
    [OldVal_Priority]                 INT           NULL,
    [InternalRefenceNotes]            VARCHAR (MAX) NULL,
    [OldVal_InternalRefenceNotes]     VARCHAR (MAX) NULL,
    [Color]                           VARCHAR (MAX) NULL,
    [OldVal_Color]                    VARCHAR (MAX) NULL,
    [SizingMethod]                    VARCHAR (MAX) NULL,
    [OldVal_SizingMethod]             VARCHAR (MAX) NULL,
    [PubPageNumber]                   VARCHAR (MAX) NULL,
    [OldVal_PubPageNumber]            VARCHAR (MAX) NULL,
    [PageCount]                       INT           NULL,
    [OldVal_PageCount]                INT           NULL,
    [NoTakeReason]                    VARCHAR (MAX) NULL,
    [OldVal_NoTakeReason]             VARCHAR (MAX) NULL,
    [Query]                           TINYINT       NULL,
    [OldVal_Query]                    TINYINT       NULL,
    [QueryCategory]                   VARCHAR (MAX) NULL,
    [OldVal_QueryCategory]            VARCHAR (MAX) NULL,
    [QueryText]                       VARCHAR (MAX) NULL,
    [OldVal_QueryText]                VARCHAR (MAX) NULL,
    [QryRaisedBy]                     VARCHAR (MAX) NULL,
    [OldVal_QryRaisedBy]              VARCHAR (MAX) NULL,
    [QryRaisedDT]                     DATETIME      NULL,
    [OldVal_QryRaisedDT]              DATETIME      NULL,
    [QueryAnswer]                     VARCHAR (MAX) NULL,
    [OldVal_QueryAnswer]              VARCHAR (MAX) NULL,
    [QryAnsweredBy]                   VARCHAR (MAX) NULL,
    [OldVal_QryAnsweredBy]            VARCHAR (MAX) NULL,
    [QryAnsweredDT]                   DATETIME      NULL,
    [OldVal_QryAnsweredDT]            DATETIME      NULL,
    [MapStatusID]                     INT           NULL,
    [OldVal_MapStatusID]              INT           NULL,
    [IndexStatusID]                   INT           NULL,
    [OldVal_IndexStatusID]            INT           NULL,
    [ScanStatusID]                    INT           NULL,
    [OldVal_ScanStatusID]             INT           NULL,
    [QCStatusID]                      INT           NULL,
    [OldVal_QCStatusID]               INT           NULL,
    [RouteStatusID]                   INT           NULL,
    [OldVal_RouteStatusID]            INT           NULL,
    [OccurrenceStatusID]              INT           NULL,
    [OldVal_OccurrenceStatusID]       INT           NULL,
    [CreateFromAuditIndicator]        TINYINT       NULL,
    [OldVal_CreateFromAuditIndicator] TINYINT       NULL,
    [FlyerID]                         INT           NULL,
    [OldVal_FlyerID]                  INT           NULL,
    [AuditBy]                         VARCHAR (MAX) NULL,
    [OldVal_AuditBy]                  VARCHAR (MAX) NULL,
    [AuditDTM]                        VARCHAR (MAX) NULL,
    [OldVal_AuditDTM]                 VARCHAR (MAX) NULL,
    [CreatedDT]                       DATETIME      NULL,
    [OldVal_CreatedDT]                DATETIME      NULL,
    [CreatedByID]                     INT           NULL,
    [OldVal_CreatedByID]              INT           NULL,
    [ModifiedDT]                      DATETIME      NULL,
    [OldVal_ModifiedDT]               DATETIME      NULL,
    [ModifiedByID]                    INT           NULL,
    [OldVal_ModifiedByID]             INT           NULL,
    CHECK ([LogDMLOperation]='U' OR [LogDMLOperation]='I' OR [LogDMLOperation]='D')
);

