CREATE TABLE [dbo].[OccurrenceDetailTVLog] (
    [LogTimeStamp]                 DATETIME         NULL,
    [LogDMLOperation]              CHAR (1)         NULL,
    [LoginUser]                    VARCHAR (32)     NULL,
    [OccurrenceDetailTVID]         BIGINT           NULL,
    [PatternID]                    INT              NULL,
    [OldVal_PatternID]             INT              NULL,
    [AdID]                         INT              NULL,
    [OldVal_AdID]                  INT              NULL,
    [TVRecordingScheduleID]        INT              NULL,
    [OldVal_TVRecordingScheduleID] INT              NULL,
    [PRCODE]                       VARCHAR (200)    NULL,
    [OldVal_PRCODE]                VARCHAR (200)    NULL,
    [AirDT]                        DATETIME         NULL,
    [OldVal_AirDT]                 DATETIME         NULL,
    [AirTime]                      TIME (7)         NULL,
    [OldVal_AirTime]               TIME (7)         NULL,
    [AdLength]                     NUMERIC (18, 10) NULL,
    [OldVal_AdLength]              NUMERIC (18, 10) NULL,
    [CaptureStationCode]           VARCHAR (200)    NULL,
    [OldVal_CaptureStationCode]    VARCHAR (200)    NULL,
    [InputFileName]                VARCHAR (200)    NULL,
    [OldVal_InputFileName]         VARCHAR (200)    NULL,
    [CaptureDT]                    DATETIME         NULL,
    [OldVal_CaptureDT]             DATETIME         NULL,
    [CreatedDT]                    DATETIME         NULL,
    [OldVal_CreatedDT]             DATETIME         NULL,
    [CapturedDT]                   DATETIME         NULL,
    [OldVal_CapturedDT]            DATETIME         NULL,
    [TVProgramID]                  VARCHAR (200)    NULL,
    [OldVal_TVProgramID]           VARCHAR (200)    NULL,
    [TVEpisodeID]                  NUMERIC (18, 10) NULL,
    [OldVal_TVEpisodeID]           NUMERIC (18, 10) NULL,
    [Deleted]                      TINYINT          NULL,
    [OldVal_Deleted]               TINYINT          NULL,
    [FakePatternCODE]              INT              NULL,
    [OldVal_FakePatternCODE]       INT              NULL,
    [CTLegacySeq]                  INT              NULL,
    [OldVal_CTLegacySeq]           INT              NULL,
    [StationID]                    INT              NULL,
    [OldVal_StationID]             INT              NULL,
    CHECK ([LogDMLOperation]='U' OR [LogDMLOperation]='I' OR [LogDMLOperation]='D')
);

