CREATE TABLE [dbo].[Publication] (
    [PublicationID]       INT            IDENTITY (1, 1) NOT NULL,
    [MarketID]            INT            NULL,
    [Descrip]             VARCHAR (50)   NULL,
    [StartDT]             DATETIME       NULL,
    [EndDT]               DATETIME       NULL,
    [Priority]            INT            NULL,
    [PublishedOn]         DATE           NULL,
    [Comments]            VARCHAR (2000) NULL,
    [ROPSizeID]           INT            NULL,
    [MagSizeID]           INT            NULL,
    [SourceID]            INT            NULL,
    [MultiEditionInd]     TINYINT        NULL,
    [PubType]             INT            NOT NULL,
    [SectionDefault]      INT            NULL,
    [CreatedDT]           DATETIME       NOT NULL,
    [CreatedByID]         INT            NOT NULL,
    [ModifiedDT]          DATETIME       NULL,
    [ModifiedByID]        INT            NULL,
    [PubCode]             VARCHAR (100)  NULL,
    [CTLegacyPubCode]     VARCHAR (4)    NULL,
    [LanguageID]          INT            NULL,
    [PubUniverseType]     INT            NULL,
    [PubWidth]            INT            NULL,
    [PubDepthLines]       INT            NULL,
    [PubDepthInches]      INT            NULL,
    [EndStatePriority]    INT            NULL,
    [Brand]               SMALLINT       NULL,
    [Promotion]           SMALLINT       NULL,
    [PubValidation]       SMALLINT       NULL,
    [CircularQueue]       SMALLINT       NULL,
    [PubQueue]            SMALLINT       NULL,
    [MultiPubQueue]       SMALLINT       NULL,
    [MultiEditionPub]     SMALLINT       NULL,
    [RecurrenceStartDate] DATE           NULL,
    [RecurrenceDays]      VARCHAR (7)    NULL,
    [RecurrenceFrequency] INT            NULL,
    [Class]               INT            NULL,
    [ColumnInch]          TINYINT        NULL,
    [Display]             TINYINT        NULL,
    [ClassifiedLineage]   TINYINT        NULL,
    [FastTrack]           TINYINT        NULL,
    [SpendUniverse]       TINYINT        NULL,
    [CoverName]           VARCHAR (50)   NULL,
    CONSTRAINT [PK_News] PRIMARY KEY CLUSTERED ([PublicationID] ASC),
    CONSTRAINT [FK_Publication_Source] FOREIGN KEY ([SourceID]) REFERENCES [dbo].[Source] ([SourceID])
);

