CREATE TABLE [dbo].[QueryDetailLog] (
    [LogTimeStamp]                 DATETIME      NULL,
    [LogDMLOperation]              CHAR (1)      NULL,
    [LoginUser]                    VARCHAR (32)  NULL,
    [QueryID]                      INT           NULL,
    [PatternMasterID]              INT           NULL,
    [OldVal_PatternMasterID]       INT           NULL,
    [PatternStgID]                 INT           NULL,
    [OldVal_PatternStgID]          INT           NULL,
    [OccurrenceID]                 VARCHAR (50)  NULL,
    [OldVal_OccurrenceID]          VARCHAR (50)  NULL,
    [PubIssueID]                   INT           NULL,
    [OldVal_PubIssueID]            INT           NULL,
    [AdID]                         INT           NULL,
    [OldVal_AdID]                  INT           NULL,
    [PromoID]                      INT           NULL,
    [OldVal_PromoID]               INT           NULL,
    [MediaStreamID]                VARCHAR (MAX) NULL,
    [OldVal_MediaStreamID]         VARCHAR (MAX) NULL,
    [System]                       VARCHAR (MAX) NULL,
    [OldVal_System]                VARCHAR (MAX) NULL,
    [EntityLevel]                  VARCHAR (MAX) NULL,
    [OldVal_EntityLevel]           VARCHAR (MAX) NULL,
    [QueryCategory]                VARCHAR (MAX) NULL,
    [OldVal_QueryCategory]         VARCHAR (MAX) NULL,
    [QueryText]                    VARCHAR (MAX) NULL,
    [OldVal_QueryText]             VARCHAR (MAX) NULL,
    [QryRaisedBy]                  INT           NULL,
    [OldVal_QryRaisedBy]           INT           NULL,
    [QryRaisedOn]                  DATETIME      NULL,
    [OldVal_QryRaisedOn]           DATETIME      NULL,
    [QryAnswer]                    VARCHAR (MAX) NULL,
    [OldVal_QryAnswer]             VARCHAR (MAX) NULL,
    [QryAnsweredBy]                INT           NULL,
    [OldVal_QryAnsweredBy]         INT           NULL,
    [QryAnsweredOn]                DATETIME      NULL,
    [OldVal_QryAnsweredOn]         DATETIME      NULL,
    [QryCreativeRepository]        VARCHAR (MAX) NULL,
    [OldVal_QryCreativeRepository] VARCHAR (MAX) NULL,
    [QryCreativeAssetName]         VARCHAR (50)  NULL,
    [OldVal_QryCreativeAssetName]  VARCHAR (50)  NULL,
    [CreatedDT]                    DATETIME      NULL,
    [OldVal_CreatedDT]             DATETIME      NULL,
    [CreatedByID]                  INT           NULL,
    [OldVal_CreatedByID]           INT           NULL,
    [ModifiedDT]                   DATETIME      NULL,
    [OldVal_ModifiedDT]            DATETIME      NULL,
    [ModifiedByID]                 INT           NULL,
    [OldVal_ModifiedByID]          INT           NULL,
    [AssignedToID]                 INT           NULL,
    [OldVal_AssignedToID]          INT           NULL,
    CHECK ([LogDMLOperation]='U' OR [LogDMLOperation]='I' OR [LogDMLOperation]='D')
);

