CREATE TABLE [dbo].[RadioStationLog] (
    [LogTimeStamp]            DATETIME     NULL,
    [LogDMLOperation]         CHAR (1)     NULL,
    [LoginUser]               VARCHAR (32) NULL,
    [RadioStationID]          INT          NULL,
    [RCSStationID]            INT          NULL,
    [OldVal_RCSStationID]     INT          NULL,
    [StationName]             VARCHAR (50) NULL,
    [OldVal_StationName]      VARCHAR (50) NULL,
    [Dma]                     INT          NULL,
    [OldVal_Dma]              INT          NULL,
    [NetworkAffiliate]        VARCHAR (50) NULL,
    [OldVal_NetworkAffiliate] VARCHAR (50) NULL,
    [LanguageID]              INT          NULL,
    [OldVal_LanguageID]       INT          NULL,
    [EthnicGroupID]           INT          NULL,
    [OldVal_EthnicGroupID]    INT          NULL,
    [Amfm]                    INT          NULL,
    [OldVal_Amfm]             INT          NULL,
    [CreatedDT]               DATETIME     NULL,
    [OldVal_CreatedDT]        DATETIME     NULL,
    [CreatedByID]             INT          NULL,
    [OldVal_CreatedByID]      INT          NULL,
    [ModifiedDT]              DATETIME     NULL,
    [OldVal_ModifiedDT]       DATETIME     NULL,
    [ModifiedByID]            INT          NULL,
    [OldVal_ModifiedByID]     INT          NULL,
    [EffectiveDT]             DATETIME     NULL,
    [OldVal_EffectiveDT]      DATETIME     NULL,
    [EndDT]                   DATETIME     NULL,
    [OldVal_EndDT]            DATETIME     NULL,
    CHECK ([LogDMLOperation]='U' OR [LogDMLOperation]='I' OR [LogDMLOperation]='D')
);

