CREATE TABLE [dbo].[RCSCreativeLog] (
    [LogTimeStamp]               DATETIME     NULL,
    [LogDMLOperation]            CHAR (1)     NULL,
    [LoginUser]                  VARCHAR (32) NULL,
    [RCSCreativeID]              VARCHAR (50) NULL,
    [OldValue_RCSCreativeID]     VARCHAR (50) NULL,
    [RCSAcctID]                  INT          NULL,
    [OldValue_RCSAcctID]         INT          NULL,
    [RCSAdvID]                   INT          NULL,
    [OldValue_RCSAdvID]          INT          NULL,
    [RCSClassID]                 INT          NULL,
    [OldValue_RCSClassID]        INT          NULL,
    [CreativeLength]             INT          NULL,
    [OldValue_CreativeLength]    INT          NULL,
    [Priority]                   INT          NULL,
    [OldValue_Priority]          INT          NULL,
    [Deleted]                    TINYINT      NULL,
    [OldValue_Deleted]           TINYINT      NULL,
    [RCSSeqForCreation]          BIGINT       NULL,
    [OldValue_RCSSeqForCreation] BIGINT       NULL,
    [CreatedDT]                  DATETIME     NULL,
    [OldValue_CreatedDT]         DATETIME     NULL,
    [CreatedByID]                INT          NULL,
    [OldValue_CreatedByID]       INT          NULL,
    [RCSSeqForUpdate]            BIGINT       NULL,
    [OldValue_RCSSeqForUpdate]   BIGINT       NULL,
    [ModifiedDT]                 DATETIME     NULL,
    [OldValue_ModifiedDT]        DATETIME     NULL,
    [ModifiedByID]               INT          NULL,
    [OldValue_ModifiedByID]      INT          NULL,
    [CTLegacyID]                 INT          NULL,
    [OldValue_CTLegacyID]        INT          NULL,
    CHECK ([LogDMLOperation]='U' OR [LogDMLOperation]='I' OR [LogDMLOperation]='D')
);

