CREATE TABLE [dbo].[RefProductLog] (
    [LogTimeStamp]               DATETIME     NULL,
    [LogDMLOperation]            CHAR (1)     NULL,
    [LoginUser]                  VARCHAR (32) NULL,
    [RefProductID]               INT          NULL,
    [AdvertiserID]               INT          NULL,
    [OldVal_AdvertiserID]        INT          NULL,
    [SubCategoryID]              INT          NULL,
    [OldVal_SubCategoryID]       INT          NULL,
    [ProductName]                VARCHAR (50) NULL,
    [OldVal_ProductName]         VARCHAR (50) NULL,
    [CreatedDT]                  DATETIME     NULL,
    [OldVal_CreatedDT]           DATETIME     NULL,
    [CreatedByID]                INT          NULL,
    [OldVal_CreatedByID]         INT          NULL,
    [ModifiedDT]                 DATETIME     NULL,
    [OldVal_ModifiedDT]          DATETIME     NULL,
    [ModifiedByID]               INT          NULL,
    [OldVal_ModifiedByID]        INT          NULL,
    [CTLegacyPRINSTCODE]         VARCHAR (10) NULL,
    [OldVal_CTLegacyPRINSTCODE]  VARCHAR (10) NULL,
    [CTLegacyPRSBCATCODE]        VARCHAR (10) NULL,
    [OldVal_CTLegacyPRSBCATCODE] VARCHAR (10) NULL,
    [CTLegacyPRCATGYCODE]        VARCHAR (10) NULL,
    [OldVal_CTLegacyPRCATGYCODE] VARCHAR (10) NULL,
    [CTLegacyPRMKTCODE]          VARCHAR (10) NULL,
    [OldVal_CTLegacyPRMKTCODE]   VARCHAR (10) NULL,
    [CTLegacyPRCODE]             VARCHAR (20) NULL,
    [OldVal_CTLegacyPRCODE]      VARCHAR (20) NULL,
    [IndustryGroup]              VARCHAR (50) NULL,
    [OldVal_IndustryGroup]       VARCHAR (50) NULL,
    [EndDate]                    DATETIME     NULL,
    [OldVal_EndDate]             DATETIME     NULL,
    [ProductShortName]           VARCHAR (50) NULL,
    [OldVal_ProductShortName]    VARCHAR (50) NULL,
    [TargetMarketID]             INT          NULL,
    [OldVal_TargetMarketID]      INT          NULL,
    [RetiredByID]                INT          NULL,
    [OldVal_RetiredByID]         INT          NULL,
    CHECK ([LogDMLOperation]='U' OR [LogDMLOperation]='I' OR [LogDMLOperation]='D')
);

