CREATE TABLE [dbo].[RefSubCategoryLog] (
    [LogTimeStamp]                DATETIME       NULL,
    [LogDMLOperation]             CHAR (1)       NULL,
    [LoginUser]                   VARCHAR (32)   NULL,
    [RefSubCategoryID]            INT            NULL,
    [CategoryID]                  INT            NULL,
    [OldVal_CategoryID]           INT            NULL,
    [SubCategoryCODE]             VARCHAR (50)   NULL,
    [OldVal_SubCategoryCODE]      VARCHAR (50)   NULL,
    [SubCategoryName]             VARCHAR (50)   NULL,
    [OldVal_SubCategoryName]      VARCHAR (50)   NULL,
    [SubCategoryShortName]        VARCHAR (50)   NULL,
    [OldVal_SubCategoryShortName] VARCHAR (50)   NULL,
    [Definition1]                 VARCHAR (1000) NULL,
    [OldVal_Definition1]          VARCHAR (1000) NULL,
    [Definition2]                 VARCHAR (1000) NULL,
    [OldVal_Definition2]          VARCHAR (1000) NULL,
    [EndDT]                       DATETIME       NULL,
    [OldVal_EndDT]                DATETIME       NULL,
    [CreatedDT]                   DATETIME       NULL,
    [OldVal_CreatedDT]            DATETIME       NULL,
    [CreatedByID]                 INT            NULL,
    [OldVal_CreatedByID]          INT            NULL,
    [ModifiedDT]                  DATETIME       NULL,
    [OldVal_ModifiedDT]           DATETIME       NULL,
    [ModifiedByID]                INT            NULL,
    [OldVal_ModifiedByID]         INT            NULL,
    [CTLegacyPSBCCODE]            VARCHAR (10)   NULL,
    [OldVal_CTLegacyPSBCCODE]     VARCHAR (10)   NULL,
    [CTLegacyPSSUCATCODE]         VARCHAR (10)   NULL,
    [OldVal_CTLegacyPSSUCATCODE]  VARCHAR (10)   NULL,
    [CTLegacyPSPCATCODE]          VARCHAR (10)   NULL,
    [OldVal_CTLegacyPSPCATCODE]   VARCHAR (10)   NULL,
    [RetiredByID]                 INT            NULL,
    [OldVal_RetiredByID]          INT            NULL,
    CHECK ([LogDMLOperation]='U' OR [LogDMLOperation]='I' OR [LogDMLOperation]='D')
);

