CREATE TABLE [dbo].[SampleRefSender] (
    [SampleRefSenderID]                               FLOAT (53)    NULL,
    [Name]                                            VARCHAR (255) NULL,
    [Address]                                         VARCHAR (255) NULL,
    [OldAddress2]                                     VARCHAR (255) NULL,
    [City]                                            VARCHAR (255) NULL,
    [State]                                           VARCHAR (255) NULL,
    [Zipcode]                                         FLOAT (53)    NULL,
    [Country]                                         VARCHAR (255) NULL,
    [Phone]                                           VARCHAR (255) NULL,
    [StartDT]                                         DATETIME      NULL,
    [EndDT]                                           DATETIME      NULL,
    [Priority]                                        FLOAT (53)    NULL,
    [ExpectedReceiveDT]                               FLOAT (53)    NULL,
    [IndNoShipping]                                   FLOAT (53)    NULL,
    [IndNoPublications]                               FLOAT (53)    NULL,
    [Comments]                                        VARCHAR (255) NULL,
    [Gender]                                          VARCHAR (255) NULL,
    [DoB]                                             VARCHAR (255) NULL,
    [AgeBracket]                                      VARCHAR (255) NULL,
    [Company]                                         VARCHAR (255) NULL,
    [ContactName]                                     VARCHAR (255) NULL,
    [MailingAddress]                                  VARCHAR (255) NULL,
    [Cell]                                            VARCHAR (255) NULL,
    [Work]                                            VARCHAR (255) NULL,
    [Phone2]                                          VARCHAR (255) NULL,
    [Email]                                           VARCHAR (255) NULL,
    [BulkLabelInd]                                    FLOAT (53)    NULL,
    [LabelQty]                                        VARCHAR (255) NULL,
    [PackageWeight]                                   VARCHAR (255) NULL,
    [LabelNote]                                       VARCHAR (255) NULL,
    [SubPayment]                                      VARCHAR (255) NULL,
    [InStoreNotes]                                    VARCHAR (255) NULL,
    [SendingInstructions]                             VARCHAR (255) NULL,
    [CCNotes]                                         VARCHAR (255) NULL,
    [EarlySender]                                     VARCHAR (255) NULL,
    [isReadyForCompare]                               VARCHAR (255) NULL,
    [DMAID]                                           VARCHAR (255) NULL,
    [IndForceQCCheck]                                 VARCHAR (255) NULL,
    [CreatedDT]                                       VARCHAR (255) NULL,
    [CreatedByID]                                     VARCHAR (255) NULL,
    [ModifiedDT]                                      VARCHAR (255) NULL,
    [ModifiedByID]                                    VARCHAR (255) NULL,
    [MTLegacySenderID]                                FLOAT (53)    NULL,
    [MTLegacyFrequencyID_(where codetypeid = 9)]      FLOAT (53)    NULL,
    [Frequency Descrip_(only for user reference)]     VARCHAR (255) NULL,
    [MTLegacyTypeID_(where codetypeid = 10)]          FLOAT (53)    NULL,
    [Type Descrip_(only for user reference)]          VARCHAR (255) NULL,
    [MTLegacyLocationID_(where codetypeid = 8)]       FLOAT (53)    NULL,
    [Location Descrip_(only for user reference)]      VARCHAR (255) NULL,
    [MTLegacyDefaultPkgAssignee]                      FLOAT (53)    NULL,
    [Assignee Name_(only for user reference)]         VARCHAR (255) NULL,
    [MTLegacyDefaultRetID]                            VARCHAR (255) NULL,
    [Retailer Descrip_(only for user reference)]      VARCHAR (255) NULL,
    [MTLegacyDefaultMarketID]                         VARCHAR (255) NULL,
    [Market Descrip_(only for user reference)]        VARCHAR (255) NULL,
    [MTLegacyShippingTypeId_(where codetypeid = 53)]  FLOAT (53)    NULL,
    [Shipping Type Descrip_(only for user reference)] VARCHAR (255) NULL,
    [MTLegacySourceID]                                FLOAT (53)    NULL,
    [Source Descrip_(only for user reference)]        VARCHAR (255) NULL,
    [Address2]                                        VARCHAR (255) NULL
);

