CREATE TABLE [dbo].[ScrapeSessionLog] (
    [LogTimeStamp]         DATETIME      NULL,
    [LogDMLOperation]      CHAR (1)      NULL,
    [LoginUser]            VARCHAR (32)  NULL,
    [ScrapeSessionID]      INT           NULL,
    [WebsiteID]            INT           NULL,
    [OldVal_WebsiteID]     INT           NULL,
    [ScrapeBeginDT]        DATETIME      NULL,
    [OldVal_ScrapeBeginDT] DATETIME      NULL,
    [ScrapeEndDT]          DATETIME      NULL,
    [OldVal_ScrapeEndDT]   DATETIME      NULL,
    [ScrapeDate]           DATE          NULL,
    [OldVal_ScrapeDate]    DATE          NULL,
    [RunWeek]              INT           NULL,
    [OldVal_RunWeek]       INT           NULL,
    [NodeID]               INT           NULL,
    [OldVal_NodeID]        INT           NULL,
    [JobID]                VARCHAR (25)  NULL,
    [OldVal_JobID]         VARCHAR (25)  NULL,
    [JobSite]              VARCHAR (100) NULL,
    [OldVal_JobSite]       VARCHAR (100) NULL,
    [ProfileName]          VARCHAR (25)  NULL,
    [OldVal_ProfileName]   VARCHAR (25)  NULL,
    [CreatedDT]            DATETIME      NULL,
    [OldVal_CreatedDT]     DATETIME      NULL,
    [ModifiedDT]           DATETIME      NULL,
    [OldVal_ModifiedDT]    DATETIME      NULL,
    CHECK ([LogDMLOperation]='U' OR [LogDMLOperation]='I' OR [LogDMLOperation]='D')
);

