CREATE TABLE [dbo].[SenderLog] (
    [LogTimeStamp]                          DATETIME      NULL,
    [LogDMLOperation]                       CHAR (1)      NULL,
    [LoginUser]                             VARCHAR (32)  NULL,
    [SenderID]                              INT           NULL,
    [Name]                                  VARCHAR (200) NULL,
    [OldVal_Name]                           VARCHAR (200) NULL,
    [Address]                               VARCHAR (200) NULL,
    [OldVal_Address]                        VARCHAR (200) NULL,
    [Address2]                              VARCHAR (50)  NULL,
    [OldVal_Address2]                       VARCHAR (50)  NULL,
    [City]                                  VARCHAR (50)  NULL,
    [OldVal_City]                           VARCHAR (50)  NULL,
    [State]                                 VARCHAR (50)  NULL,
    [OldVal_State]                          VARCHAR (50)  NULL,
    [ZipCode]                               VARCHAR (50)  NULL,
    [OldVal_ZipCode]                        VARCHAR (50)  NULL,
    [Country]                               VARCHAR (50)  NULL,
    [OldVal_Country]                        VARCHAR (50)  NULL,
    [Phone]                                 VARCHAR (50)  NULL,
    [OldVal_Phone]                          VARCHAR (50)  NULL,
    [StartDT]                               DATETIME      NULL,
    [OldVal_StartDT]                        DATETIME      NULL,
    [EndDT]                                 DATETIME      NULL,
    [OldVal_EndDT]                          DATETIME      NULL,
    [Priority]                              INT           NULL,
    [OldVal_Priority]                       INT           NULL,
    [FrequencyID]                           INT           NULL,
    [OldVal_FrequencyID]                    INT           NULL,
    [ExpectedReceiveDT]                     INT           NULL,
    [OldVal_ExpectedReceiveDT]              INT           NULL,
    [TypeID]                                INT           NULL,
    [OldVal_TypeID]                         INT           NULL,
    [LocationID]                            INT           NULL,
    [OldVal_LocationID]                     INT           NULL,
    [IndNoShipping]                         TINYINT       NULL,
    [OldVal_IndNoShipping]                  TINYINT       NULL,
    [IndNoPublications]                     TINYINT       NULL,
    [OldVal_IndNoPublications]              TINYINT       NULL,
    [Comments]                              VARCHAR (250) NULL,
    [OldVal_Comments]                       VARCHAR (250) NULL,
    [DefaultPkgAssignee]                    INT           NULL,
    [OldVal_DefaultPkgAssignee]             INT           NULL,
    [DefaultRetID]                          INT           NULL,
    [OldVal_DefaultRetID]                   INT           NULL,
    [DefaultMktID]                          INT           NULL,
    [OldVal_DefaultMktID]                   INT           NULL,
    [Gender]                                VARCHAR (50)  NULL,
    [OldVal_Gender]                         VARCHAR (50)  NULL,
    [DoB]                                   DATETIME      NULL,
    [OldVal_DoB]                            DATETIME      NULL,
    [AgeBracket]                            VARCHAR (50)  NULL,
    [OldVal_AgeBracket]                     VARCHAR (50)  NULL,
    [Company]                               VARCHAR (200) NULL,
    [OldVal_Company]                        VARCHAR (200) NULL,
    [ContactName]                           VARCHAR (200) NULL,
    [OldVal_ContactName]                    VARCHAR (200) NULL,
    [MailingAddress]                        VARCHAR (500) NULL,
    [OldVal_MailingAddress]                 VARCHAR (500) NULL,
    [Cell]                                  VARCHAR (100) NULL,
    [OldVal_Cell]                           VARCHAR (100) NULL,
    [Work]                                  VARCHAR (100) NULL,
    [OldVal_Work]                           VARCHAR (100) NULL,
    [Phone2]                                VARCHAR (100) NULL,
    [OldVal_Phone2]                         VARCHAR (100) NULL,
    [Email]                                 VARCHAR (100) NULL,
    [OldVal_Email]                          VARCHAR (100) NULL,
    [ShippingTypeID]                        INT           NULL,
    [OldVal_ShippingTypeID]                 INT           NULL,
    [BulkLabelInd]                          TINYINT       NULL,
    [OldVal_BulkLabelInd]                   TINYINT       NULL,
    [LabelQty]                              VARCHAR (100) NULL,
    [OldVal_LabelQty]                       VARCHAR (100) NULL,
    [PackageWeight]                         VARCHAR (100) NULL,
    [OldVal_PackageWeight]                  VARCHAR (100) NULL,
    [LabelNote]                             VARCHAR (500) NULL,
    [OldVal_LabelNote]                      VARCHAR (500) NULL,
    [SubPayment]                            INT           NULL,
    [OldVal_SubPayment]                     INT           NULL,
    [InStoreNotes]                          VARCHAR (500) NULL,
    [OldVal_InStoreNotes]                   VARCHAR (500) NULL,
    [SendingInstructions]                   VARCHAR (500) NULL,
    [OldVal_SendingInstructions]            VARCHAR (500) NULL,
    [CCNotes]                               VARCHAR (500) NULL,
    [OldVal_CCNotes]                        VARCHAR (500) NULL,
    [EarlySender]                           INT           NULL,
    [OldVal_EarlySender]                    INT           NULL,
    [SourceID]                              INT           NULL,
    [OldVal_SourceID]                       INT           NULL,
    [DigitalOnlyIndicator]                  TINYINT       NULL,
    [OldVal_DigitalOnlyIndicator]           TINYINT       NULL,
    [CreatedDT]                             DATETIME      NULL,
    [OldVal_CreatedDT]                      DATETIME      NULL,
    [CreatedByID]                           INT           NULL,
    [OldVal_CreatedByID]                    INT           NULL,
    [ModifiedDT]                            DATETIME      NULL,
    [OldVal_ModifiedDT]                     DATETIME      NULL,
    [ModifiedByID]                          INT           NULL,
    [OldVal_ModifiedByID]                   INT           NULL,
    [MTLegacyDefaultRetID]                  INT           NULL,
    [OldVal_MTLegacyDefaultRetID]           INT           NULL,
    [MTLegacyDefaultMarketID]               INT           NULL,
    [OldVal_MTLegacyDefaultMarketID]        INT           NULL,
    [TypeDescrip]                           VARCHAR (255) NULL,
    [OldVal_TypeDescrip]                    VARCHAR (255) NULL,
    [LocationDescrip]                       VARCHAR (255) NULL,
    [OldVal_LocationDescrip]                VARCHAR (255) NULL,
    [ShippingTypeDescrip]                   VARCHAR (255) NULL,
    [OldVal_ShippingTypeDescrip]            VARCHAR (255) NULL,
    [RetailerDescription]                   VARCHAR (255) NULL,
    [OldVal_RetailerDescription]            VARCHAR (255) NULL,
    [SIMRInd]                               TINYINT       NULL,
    [OldVal_SIMRInd]                        TINYINT       NULL,
    [ReadyForCompare]                       TINYINT       NULL,
    [OldVal_ReadyForCompare]                TINYINT       NULL,
    [DMAID]                                 INT           NULL,
    [OldVal_DMAID]                          INT           NULL,
    [MTLegacySenderID]                      INT           NULL,
    [OldVal_MTLegacySenderID]               INT           NULL,
    [MTLegacyDefaultPkgAssigneeCODE]        VARCHAR (50)  NULL,
    [OldVal_MTLegacyDefaultPkgAssigneeCODE] VARCHAR (50)  NULL,
    [AssigneeName]                          VARCHAR (100) NULL,
    [OldVal_AssigneeName]                   VARCHAR (100) NULL,
    [AdvertiserID]                          INT           NULL,
    [OldVal_AdvertiserID]                   INT           NULL,
    [MarketID]                              INT           NULL,
    [OldVal_MarketID]                       INT           NULL,
    [MarketDescrip]                         VARCHAR (255) NULL,
    [OldVal_MarketDescrip]                  VARCHAR (255) NULL,
    [SourceDescrip]                         VARCHAR (255) NULL,
    [OldVal_SourceDescrip]                  VARCHAR (255) NULL,
    [FrequencyDescrip]                      VARCHAR (255) NULL,
    [OldVal_FrequencyDescrip]               VARCHAR (255) NULL,
    CHECK ([LogDMLOperation]='U' OR [LogDMLOperation]='I' OR [LogDMLOperation]='D')
);

