CREATE TABLE [dbo].[TVMMPRCodeLog] (
    [LogTimeStamp]                 DATETIME      NULL,
    [LogDMLOperation]              CHAR (1)      NULL,
    [LoginUser]                    VARCHAR (32)  NULL,
    [TVMMPRCodeCODE]               VARCHAR (200) NULL,
    [ApprovedMarketID]             INT           NULL,
    [OldVal_ApprovedMarketID]      INT           NULL,
    [OriginalPatternCode]          VARCHAR (200) NULL,
    [OldVal_OriginalPatternCode]   VARCHAR (200) NULL,
    [ApprovedForAllMarkets]        TINYINT       NULL,
    [OldVal_ApprovedForAllMarkets] TINYINT       NULL,
    [EffectiveStartDT]             DATETIME      NULL,
    [OldVal_EffectiveStartDT]      DATETIME      NULL,
    [EffectiveEndDT]               DATETIME      NULL,
    [OldVal_EffectiveEndDT]        DATETIME      NULL,
    [CreatedDT]                    DATETIME      NULL,
    [OldVal_CreatedDT]             DATETIME      NULL,
    [CreatedByID]                  INT           NULL,
    [OldVal_CreatedByID]           INT           NULL,
    [ModifiedDT]                   DATETIME      NULL,
    [OldVal_ModifiedDT]            DATETIME      NULL,
    [Status]                       VARCHAR (200) NULL,
    [OldVal_Status]                VARCHAR (200) NULL,
    [AdID]                         INT           NULL,
    [OldVal_AdID]                  INT           NULL,
    [MediaStream]                  VARCHAR (20)  NULL,
    [OldVal_MediaStream]           VARCHAR (20)  NULL,
    CHECK ([LogDMLOperation]='U' OR [LogDMLOperation]='I' OR [LogDMLOperation]='D')
);

