CREATE TABLE [dbo].[WebsiteLog] (
    [LogTimeStamp]              DATETIME       NULL,
    [LogDMLOperation]           CHAR (1)       NULL,
    [LoginUser]                 VARCHAR (32)   NULL,
    [WebsiteID]                 INT            NULL,
    [SiteID]                    VARCHAR (32)   NULL,
    [OldVal_SiteID]             VARCHAR (32)   NULL,
    [SiteName]                  VARCHAR (256)  NULL,
    [OldVal_SiteName]           VARCHAR (256)  NULL,
    [ParentSiteID]              VARCHAR (32)   NULL,
    [OldVal_ParentSiteID]       VARCHAR (32)   NULL,
    [SiteURL]                   VARCHAR (1024) NULL,
    [OldVal_SiteURL]            VARCHAR (1024) NULL,
    [ActiveStatus]              VARCHAR (3)    NULL,
    [OldVal_ActiveStatus]       VARCHAR (3)    NULL,
    [MarketCode]                VARCHAR (4)    NULL,
    [OldVal_MarketCode]         VARCHAR (4)    NULL,
    [EthnicFlag]                SMALLINT       NULL,
    [OldVal_EthnicFlag]         SMALLINT       NULL,
    [SpendFlag]                 VARCHAR (1)    NULL,
    [OldVal_SpendFlag]          VARCHAR (1)    NULL,
    [RedirctURL]                VARCHAR (1024) NULL,
    [OldVal_RedirctURL]         VARCHAR (1024) NULL,
    [TopSite]                   VARCHAR (3)    NULL,
    [OldVal_TopSite]            VARCHAR (3)    NULL,
    [WebsiteAffiliation]        VARCHAR (256)  NULL,
    [OldVal_WebsiteAffiliation] VARCHAR (256)  NULL,
    [MediaOutletGenreID]        INT            NULL,
    [OldVal_MediaOutletGenreID] INT            NULL,
    [CreatedDT]                 DATETIME       NULL,
    [OldVal_CreatedDT]          DATETIME       NULL,
    [EditedDT]                  DATETIME       NULL,
    [OldVal_EditedDT]           DATETIME       NULL,
    [EditedInitials]            VARCHAR (3)    NULL,
    [OldVal_EditedInitials]     VARCHAR (3)    NULL,
    [CTLegacySeq]               INT            NULL,
    [OldVal_CTLegacySeq]        INT            NULL,
    CHECK ([LogDMLOperation]='U' OR [LogDMLOperation]='I' OR [LogDMLOperation]='D')
);

