CREATE TABLE [dbo].[WhatWeTakeLog] (
    [LogTimeStamp]               DATETIME      NULL,
    [LogDMLOperation]            CHAR (1)      NULL,
    [LoginUser]                  VARCHAR (32)  NULL,
    [WhatWeTakeID]               INT           NULL,
    [WWTIndustryID]              INT           NULL,
    [OldVal_WWTIndustryID]       INT           NULL,
    [AdvertiserID]               INT           NULL,
    [OldVal_AdvertiserID]        INT           NULL,
    [MediaStream]                INT           NULL,
    [OldVal_MediaStream]         INT           NULL,
    [MediaStreamGroupID]         INT           NULL,
    [OldVal_MediaStreamGroupID]  INT           NULL,
    [PubGroupID]                 INT           NULL,
    [OldVal_PubGroupID]          INT           NULL,
    [MarketID]                   INT           NULL,
    [OldVal_MarketID]            INT           NULL,
    [PublicationID]              INT           NULL,
    [OldVal_PublicationID]       INT           NULL,
    [WWTRuleID]                  INT           NULL,
    [OldVal_WWTRuleID]           INT           NULL,
    [PromotionAdLevel]           INT           NULL,
    [OldVal_PromotionAdLevel]    INT           NULL,
    [PromotionConsumable]        INT           NULL,
    [OldVal_PromotionConsumable] INT           NULL,
    [PromotionDurables]          INT           NULL,
    [OldVal_PromotionDurables]   INT           NULL,
    [Ethnicity]                  VARCHAR (100) NULL,
    [OldVal_Ethnicity]           VARCHAR (100) NULL,
    [PubTracking]                VARCHAR (100) NULL,
    [OldVal_PubTracking]         VARCHAR (100) NULL,
    [PrimaryPub]                 VARCHAR (100) NULL,
    [OldVal_PrimaryPub]          VARCHAR (100) NULL,
    [EffectiveDT]                DATETIME      NULL,
    [OldVal_EffectiveDT]         DATETIME      NULL,
    [EndDT]                      DATETIME      NULL,
    [OldVal_EndDT]               DATETIME      NULL,
    [CreatedDT]                  DATETIME      NULL,
    [OldVal_CreatedDT]           DATETIME      NULL,
    [CreatedByID]                INT           NULL,
    [OldVal_CreatedByID]         INT           NULL,
    [ModifiedDT]                 DATETIME      NULL,
    [OldVal_ModifiedDT]          DATETIME      NULL,
    [ModifiedByID]               INT           NULL,
    [OldVal_ModifiedByID]        INT           NULL,
    CHECK ([LogDMLOperation]='U' OR [LogDMLOperation]='I' OR [LogDMLOperation]='D')
);

