-- =============================================   
-- Author:    Govardhan   
-- Create date: 05/22/2015   
-- Description: Process Ingestion for Netwrok Program national weekly file.  
-- Query :   
/*  

exec sp_NIELSONInsertNRTProgramNWFileData '',  

*/ 
-- =============================================   
CREATE PROCEDURE [dbo].[sp_NIELSONInsertNRTProgramNWFileData_withoutLookup] (@NIELSONINGNWData dbo.NIELSONINGNWData 
readonly) 
AS 
  BEGIN 
      SET nocount ON; 

      BEGIN try 
          BEGIN TRANSACTION 

        --INSERT PROGRAM DATA--

		truncate table NLSNProgramScheduleTemp;

		insert into NLSNProgramScheduleTemp([MarketID],Channel,AirDate,ProgramName,StartTime,EndTime,[QuarterHourID],[CreatedDT],[CreatedByID])

		select 1[MARKETCODE],FILTER.ACNNETWORKCODE,FILTER.AIRDATE,FILTER.PROGRAMNAME,FILTER.STARTTIME,FILTER.ENDTIME,
		(SELECT QuarterHourID from QuarterHour WHERE cast(convert(datetime,SUBSTRING(FILTER.STARTTIME,1,2)+':'+SUBSTRING(FILTER.STARTTIME,3,2)) as time) BETWEEN StartTime and EndTime )
		[QUARTERHOURID],GETDATE()[CREATEDDATE],1[CREATEDBY] FROM 
		(
		SELECT 
		SUBSTRING(VALUE,15,6)[ACNNETWORKCODE],
		SUBSTRING(VALUE,44,7)[AIRDATE], 
		SUBSTRING(VALUE,86,4)[STARTTIME],
		SUBSTRING(VALUE,278,4)[EVENTDURATION]
		,
		(select REPLACE(CONVERT(VARCHAR(8), DATEVALUE, 108), ':', '')
		from (
		SELECT DATEADD(SECOND,-1,DATEVALUE)[DATEVALUE] FROM (
		select  DATEADD(MINUTE,(convert(int,SUBSTRING(VALUE,278,4))),CAST(
									(   SUBSTRING(SUBSTRING(VALUE,86,4), 1, 2) + ':' + 
										SUBSTRING(SUBSTRING(VALUE,86,4), 3, 2)
									) AS DATETIME
								)
							) AS DATEVALUE) AS SUB
							) Filter)[ENDTIME]
		,
		SUBSTRING(VALUE,115,25)[PROGRAMNAME]
		FROM 
		@NIELSONINGNWData PN
		WHERE SUBSTRING(VALUE,11,1)=0
		AND SUBSTRING(VALUE,42,2)=00
		AND (SUBSTRING(VALUE,97,1)=NULL 
		OR (SUBSTRING(VALUE,97,1)=''))
		AND SUBSTRING(VALUE,85,1)='D'
		AND SUBSTRING(VALUE,1,2)='04'
		and Convert(int,(SUBSTRING(VALUE,86,4)))<2400
		)AS FILTER

		insert into NLSNProgramSchedule([MarketID],Channel,[AirDT],ProgramName,StartTime,EndTime,[QuarterHourID],[CreatedDT],[CreatedByID])

		select MarketID,Channel,convert(datetime,'20'+substring(AirDate,2,6))[AirDate],ProgramName,
		cast(convert(datetime,SUBSTRING(STARTTIME,1,2)+':'+SUBSTRING(STARTTIME,3,2)) as time)[StartTime],
		cast(convert(datetime,SUBSTRING(ENDTIME,1,2)+':'+SUBSTRING(ENDTIME,3,2)) as time)[EndTime],
		[QuarterHourID],getdate(),1 FROM 
		(		
		SELECT 1[MarketID],Channel,CASE WHEN CONVERT(INT,STARTTIME)<600 THEN CONVERT(VARCHAR(8),(CONVERT(INT,AIRDATE)-1)) ELSE AIRDATE END AS [AIRDATE],ProgramName,DBO.NIELSONROUNDOFFSTARTTIME(STARTTIME) AS STARTTIME,DBO.NIELSONRoundOffEndTime(ENDTIME) AS ENDTIME,[QuarterHourID]
		FROM NLSNProgramScheduleTemp
		)SUB
 
        --INSERT HOUSEHOLD AND DEMOGRAPHIC DATA--

		--Table variable to hold filtered household data.
		DECLARE @HHFILTEREDData TABLE
		(
		  ACNNETWORKCODE VARCHAR(50), 
		  AIRDATE VARCHAR(50),
		  STARTTIME VARCHAR(50),
		  ENDTIME VARCHAR(50),
		  FIRSTQUARTERHOURDURATION VARCHAR(50),
		  SECONDQUARTERHOURDURATION VARCHAR(50),
		  HHFIRST VARCHAR(50),
		  HHSECOND VARCHAR(50),
		  HalfHourIdentifier VARCHAR(50)
		);

		--Table variable to hold filtered household calculated data.
		DECLARE @HHCALCULATIONRESULT TABLE
		(
		  ACNNETWORKCODE VARCHAR(50), 
		  AIRDATE VARCHAR(50),
		  HalfHourIdentifier VARCHAR(50),
		  HHFIRST VARCHAR(50),
		  HHSECOND VARCHAR(50),
		  QUARTERHOURIDENTIFIER VARCHAR(50),
		  STARTTIME VARCHAR(50)
		);

		--Table variable to hold final household data.
		DECLARE @HHFINALRESULT TABLE
		(
		  ACNNETWORKCODE VARCHAR(50), 
		  AIRDATE VARCHAR(50),
		  STARTTIME VARCHAR(50),
		  ENDTIME VARCHAR(50),
		  HalfHourIdentifier VARCHAR(50),
		  QUARTERHOURIDENTIFIER VARCHAR(50),
		  HOUSEHOLDVALUE BIGINT
		  );
        
		--DUPLICATE TABLE
		DECLARE @DOUBLE TABLE
		(
		  SlNo INT
		);
		INSERT INTO @DOUBLE(SlNo)
		SELECT SlNo
		FROM (
		select 1[SlNo]
		union
		select 2[SlNo]
		)AS FILTER;

		---DEMOGRAPHIC VARIABLES---

		DECLARE @DMFILTEREDDATA TABLE
		(
		  NETWORKCODE VARCHAR(50), 
		  AIRDATE VARCHAR(50),
		  STARTTIME VARCHAR(50),
		  ENDTIME VARCHAR(50),
		  QUARTERHOURIDENTIFIER VARCHAR(50),
		  DEMOGRAPHICGROUPID VARCHAR(50),
		  FC2_5 VARCHAR(50),
		  FC6_8 VARCHAR(50),
		  FC9_11 VARCHAR(50),
		  FT12_14 VARCHAR(50),
		  FT15_17 VARCHAR(50),
		  F18_20 VARCHAR(50),
		  F21_24 VARCHAR(50),
		  F25_29 VARCHAR(50),
		  F30_34 VARCHAR(50),
		  F35_39 VARCHAR(50),
		  F40_44 VARCHAR(50),
		  F45_49 VARCHAR(50),
		  F50_54 VARCHAR(50),
		  F55_64 VARCHAR(50),
		  F65PLUS VARCHAR(50),
		  MC2_5 VARCHAR(50),
		  MC6_8 VARCHAR(50),
		  MC9_11 VARCHAR(50),
		  MT12_14 VARCHAR(50),
		  MT15_17 VARCHAR(50),
		  M18_20 VARCHAR(50),
		  M21_24 VARCHAR(50),
		  M25_29 VARCHAR(50),
		  M30_34 VARCHAR(50),
		  M35_39 VARCHAR(50),
		  M40_44 VARCHAR(50),
		  M45_49 VARCHAR(50),
		  M50_54 VARCHAR(50),
		  M55_64 VARCHAR(50),
		  M65PLUS VARCHAR(50)
		  );

		DECLARE @DMCALCULATEDDATA TABLE
		(
		  NETWORKCODE VARCHAR(50), 
		  AIRDATE VARCHAR(50),
		  QUARTERHOURIDENTIFIER VARCHAR(50),
		  DEMOGRAPHICGROUPID VARCHAR(50),
		  FC2_5 VARCHAR(50),
		  FC6_8 VARCHAR(50),
		  FC9_11 VARCHAR(50),
		  FT12_14 VARCHAR(50),
		  FT15_17 VARCHAR(50),
		  F18_20 VARCHAR(50),
		  F21_24 VARCHAR(50),
		  F25_29 VARCHAR(50),
		  F30_34 VARCHAR(50),
		  F35_39 VARCHAR(50),
		  F40_44 VARCHAR(50),
		  F45_49 VARCHAR(50),
		  F50_54 VARCHAR(50),
		  F55_64 VARCHAR(50),
		  F65PLUS VARCHAR(50),
		  MC2_5 VARCHAR(50),
		  MC6_8 VARCHAR(50),
		  MC9_11 VARCHAR(50),
		  MT12_14 VARCHAR(50),
		  MT15_17 VARCHAR(50),
		  M18_20 VARCHAR(50),
		  M21_24 VARCHAR(50),
		  M25_29 VARCHAR(50),
		  M30_34 VARCHAR(50),
		  M35_39 VARCHAR(50),
		  M40_44 VARCHAR(50),
		  M45_49 VARCHAR(50),
		  M50_54 VARCHAR(50),
		  M55_64 VARCHAR(50),
		  M65PLUS VARCHAR(50)
		  );

		DECLARE @DEMOGRAPHICDIVIDER AS INT;
		SET @DEMOGRAPHICDIVIDER=30;

		---INSERT HOUSEHOLD FILTERED DATA.
		INSERT INTO @HHFILTEREDData(ACNNETWORKCODE,AIRDATE,STARTTIME,FIRSTQUARTERHOURDURATION,SECONDQUARTERHOURDURATION,ENDTIME,HHFIRST,HHSECOND,HalfHourIdentifier)
		SELECT 
		SUBSTRING(VALUE,15,6)[ACNNETWORKCODE],
		SUBSTRING(VALUE,44,7)[AIRDATE], 
		SUBSTRING(VALUE,86,4)[STARTTIME],
		SUBSTRING(VALUE,254,6)[FIRSTQUARTERHOURDURATION],
		SUBSTRING(VALUE,303,6)[SECONDQUARTERHOURDURATION],
		''[ENDTIME],
		SUBSTRING(VALUE,260,9)[HHFIRST], 
		SUBSTRING(VALUE,309,9)[HHSECOND],
		SUBSTRING(VALUE,81,2)[HalfHourIdentifier]
		FROM
		@NIELSONINGNWData PN
		WHERE SUBSTRING(VALUE,11,1)=0
		AND SUBSTRING(VALUE,42,2)=00
		AND (SUBSTRING(VALUE,97,1)=NULL 
		OR (SUBSTRING(VALUE,97,1)=''))
		--AND SUBSTRING(VALUE,DBO.GetStartIndexOfNLSNINGAttribute('NPRHouseholdData','Half Hour Identifier'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRHouseholdData','Half Hour Identifier'),1))>0
		AND SUBSTRING(VALUE,85,1)='H';

		--INSERT HOUSEHOLD CALCULATED DATA.
		INSERT INTO @HHCALCULATIONRESULT(ACNNETWORKCODE,AIRDATE,HalfHourIdentifier,HHFIRST,HHSECOND,QUARTERHOURIDENTIFIER,STARTTIME)

		SELECT ACNNETWORKCODE,AIRDATE,HALFHOURIDENTIFIER,HHFIRST,HHSECOND,
		(SELECT q.QuarterHourID from QuarterHour q WHERE cast(convert(datetime,SUBSTRING(FILTER.STARTTIME,1,2)+':'+SUBSTRING(FILTER.STARTTIME,3,2)) as time) BETWEEN q.StartTime and q.EndTime )[QUARTERHOURIDENTIFIER],
		STARTTIME
		 FROM 
		(select CD.ACNNETWORKCODE,CD.AIRDATE,CD.HalfHourIdentifier,count(*)[Count],
		(sum(isnull(convert(bigint,CD.FIRSTQUARTERHOURDURATION),0)*isnull(CD.HHFIRST,0))/sum(convert(bigint,CD.FIRSTQUARTERHOURDURATION)))[HHFIRST],
		(sum(isnull(convert(bigint,CD.SECONDQUARTERHOURDURATION),0)*isnull(CD.HHSECOND,0))/sum(convert(bigint,CD.SECONDQUARTERHOURDURATION)))[HHSECOND],
		(SELECT TOP 1 STARTTIME FROM @HHFILTEREDData WHERE ACNNETWORKCODE=CD.ACNNETWORKCODE AND AIRDATE=CD.AIRDATE AND HalfHourIdentifier=CD.HalfHourIdentifier)[STARTTIME] 
		from @HHFILTEREDData CD
		WHERE CD.FIRSTQUARTERHOURDURATION<>0 AND CD.SECONDQUARTERHOURDURATION<>0
		AND Convert(int,CD.STARTTIME)<2400
		group by ACNNETWORKCODE,AIRDATE,HalfHourIdentifier
		) FILTER;

		--INSERT FINAL HOUSE HOLD RESULT DATA.
		INSERT INTO @HHFINALRESULT(ACNNETWORKCODE,AIRDATE,STARTTIME,ENDTIME,HalfHourIdentifier,QUARTERHOURIDENTIFIER,HOUSEHOLDVALUE)
		SELECT CR.ACNNETWORKCODE,CR.AIRDATE,
		CASE WHEN CD.SLNO=1 THEN CR.STARTTIME 
		     WHEN CD.SLNO=2 THEN
			 (select REPLACE(CONVERT(VARCHAR(5), DATEVALUE, 108), ':', '')
		from (	  select  DATEADD(MINUTE,(convert(int,15)),CAST(
									(   SUBSTRING(CR.STARTTIME, 1, 2) + ':' + 
										SUBSTRING(CR.STARTTIME, 3, 2)
									) AS DATETIME
								)
							) AS DATEVALUE) AS SUB)
							
							 END
		[STARTTIME],

			CASE WHEN CD.SLNO=1 THEN 
			
			(select REPLACE(CONVERT(VARCHAR(8), DATEVALUE, 108), ':', '')
		from (
		SELECT DATEADD(SECOND,59,DATEVALUE)[DATEVALUE] FROM (
		select  DATEADD(MINUTE,(convert(int,14)),CAST(
									(   SUBSTRING(CR.STARTTIME, 1, 2) + ':' + 
										SUBSTRING(CR.STARTTIME, 3, 2)
									) AS DATETIME
								)
							) AS DATEVALUE) AS SUB
							) Filter)
			
			
			 
		     WHEN CD.SLNO=2 THEN
			(select REPLACE(CONVERT(VARCHAR(8), DATEVALUE, 108), ':', '')
		from (
		SELECT DATEADD(SECOND,59,DATEVALUE)[DATEVALUE] FROM (
		select  DATEADD(MINUTE,(convert(int,29)),CAST(
									(   SUBSTRING(CR.STARTTIME, 1, 2) + ':' + 
										SUBSTRING(CR.STARTTIME, 3, 2)
									) AS DATETIME
								)
							) AS DATEVALUE) AS SUB
							) Filter)
							
							 END
            [ENDTIME],CR.HALFHOURIDENTIFIER,(CASE WHEN CD.SLNO=1 THEN CR.QUARTERHOURIDENTIFIER WHEN CD.SLNO=2 THEN CR.QUARTERHOURIDENTIFIER+1 END)[QUARTERHOURIDENTIFIER] 
		,(CASE WHEN CD.SLNO=1 THEN CR.HHFIRST WHEN CD.SLNO=2 THEN CR.HHSECOND END)[HOUSEHOLDVALUE] FROM 
		@HHCALCULATIONRESULT CR,
		@DOUBLE CD

		--INSERT FILTERED DEMOGRAPHIC DATA.
		INSERT INTO @DMFILTEREDDATA(NETWORKCODE,AIRDATE,STARTTIME,ENDTIME,QUARTERHOURIDENTIFIER,DEMOGRAPHICGROUPID,FC2_5,FC6_8,FC9_11,FT12_14,FT15_17,F18_20,F21_24,F25_29,
		F30_34,F35_39,F40_44,F45_49,F50_54,F55_64,F65PLUS,MC2_5,MC6_8,MC9_11,MT12_14,MT15_17,
		M18_20,M21_24,M25_29,M30_34,M35_39,M40_44,M45_49,M50_54,M55_64,M65PLUS
		)
		SELECT SUBSTRING(VALUE,15,6)[NETWORKCODE],
		SUBSTRING(VALUE,44,7)[AIRDATE], 
		SUBSTRING(VALUE,86,4)[STARTTIME],
		''[ENDTIME],
		CASE WHEN SUBSTRING(VALUE,92,3)='001' THEN 
		(SELECT QuarterHourID from QuarterHour 
		WHERE cast(convert(datetime,SUBSTRING((SUBSTRING(VALUE,86,4)),1,2)+':'+
		SUBSTRING((SUBSTRING(VALUE,86,4)),3,2)) as time) 
		BETWEEN StartTime and EndTime )
		WHEN SUBSTRING(VALUE,92,3)='021' THEN (SELECT QuarterHourID+1 from QuarterHour 
		WHERE cast(convert(datetime,SUBSTRING((SUBSTRING(VALUE,86,4)),1,2)+':'+
		SUBSTRING((SUBSTRING(VALUE,86,4)),3,2)) as time) 
		BETWEEN StartTime and EndTime ) END
		[QUARTERHOURIDENTIFIER],
		--SUBSTRING(VALUE,DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','Quarter Hour Identifier'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','Quarter Hour Identifier'),1))[QUARTERHOURIDENTIFIER],
		SUBSTRING(VALUE,92,3)[DEMOGRAPHICGROUPID],
		CASE WHEN SUBSTRING(VALUE,92,3)='001' THEN 
		SUBSTRING(VALUE,116,9)
		END [FC2_5],
		CASE WHEN SUBSTRING(VALUE,92,3)='001' THEN 
		SUBSTRING(VALUE,125,9)
		END[FC6_8],
		CASE WHEN SUBSTRING(VALUE,92,3)='001' THEN 
		SUBSTRING(VALUE,134,9)
		END[FC9_11],
		CASE WHEN SUBSTRING(VALUE,92,3)='001' THEN 
		SUBSTRING(VALUE,143,9)
		END[FT12_14],
		CASE WHEN SUBSTRING(VALUE,92,3)='001' THEN 
		SUBSTRING(VALUE,152,9)
		END[FT15_17],
		CASE WHEN SUBSTRING(VALUE,92,3)='001' THEN 
		SUBSTRING(VALUE,161,9)
		END[F18_20],
		CASE WHEN SUBSTRING(VALUE,92,3)='001' THEN 
		SUBSTRING(VALUE,170,9)
		END[F21_24],
		CASE WHEN SUBSTRING(VALUE,92,3)='001' THEN 
		SUBSTRING(VALUE,179,9)
		END[F25_29],
		CASE WHEN SUBSTRING(VALUE,92,3)='001' THEN 
		SUBSTRING(VALUE,188,9)
		END[F30_34],
		CASE WHEN SUBSTRING(VALUE,92,3)='001' THEN 
		SUBSTRING(VALUE,197,9)
		END[F35_39],
		CASE WHEN SUBSTRING(VALUE,92,3)='001' THEN 
		SUBSTRING(VALUE,206,9)
		END[F40_44],
		CASE WHEN SUBSTRING(VALUE,92,3)='001' THEN 
		SUBSTRING(VALUE,215,9)
		END[F45_49],
		CASE WHEN SUBSTRING(VALUE,92,3)='001' THEN 
		SUBSTRING(VALUE,224,9)
		END[F50_54],
		CASE WHEN SUBSTRING(VALUE,92,3)='001' THEN 
		SUBSTRING(VALUE,233,9)
		END[F55_64],
		CASE WHEN SUBSTRING(VALUE,92,3)='001' THEN 
		SUBSTRING(VALUE,242,9)
		END[F65PLUS],
		CASE WHEN SUBSTRING(VALUE,92,3)='001' THEN 
		SUBSTRING(VALUE,251,9)
		END[MC2_5],
		CASE WHEN SUBSTRING(VALUE,92,3)='001' THEN 
		SUBSTRING(VALUE,260,9)
		END[MC6_8],
		CASE WHEN SUBSTRING(VALUE,92,3)='001' THEN 
		SUBSTRING(VALUE,269,9)
		END[MC9_11],
		CASE WHEN SUBSTRING(VALUE,92,3)='001' THEN 
		SUBSTRING(VALUE,278,9)
		END[MT12_14],
		CASE WHEN SUBSTRING(VALUE,92,3)='001' THEN 
		SUBSTRING(VALUE,287,9)
		END[MT15_17],
		CASE WHEN SUBSTRING(VALUE,92,3)='021' THEN 
		SUBSTRING(VALUE,116,9)
		END[M18_20],
		CASE WHEN SUBSTRING(VALUE,92,3)='021' THEN 
		SUBSTRING(VALUE,125,9)
		END[M21_24],
		CASE WHEN SUBSTRING(VALUE,92,3)='021' THEN 
		SUBSTRING(VALUE,134,9)
		END[M25_29],
		CASE WHEN SUBSTRING(VALUE,92,3)='021' THEN 
		SUBSTRING(VALUE,143,9)
		END[M30_34],
		CASE WHEN SUBSTRING(VALUE,92,3)='021' THEN 
		SUBSTRING(VALUE,152,9)
		END[M35_39],
		CASE WHEN SUBSTRING(VALUE,92,3)='021' THEN 
		SUBSTRING(VALUE,161,9)
		END[M40_44],
		CASE WHEN SUBSTRING(VALUE,92,3)='021' THEN 
		SUBSTRING(VALUE,170,9)
		END[M45_49],
		CASE WHEN SUBSTRING(VALUE,92,3)='021' THEN 
		SUBSTRING(VALUE,179,9)
		END[M50_54],
		CASE WHEN SUBSTRING(VALUE,92,3)='021' THEN 
		SUBSTRING(VALUE,188,9)
		END[M55_64],
		CASE WHEN SUBSTRING(VALUE,92,3)='021' THEN 
		SUBSTRING(VALUE,197,9)
		END[M65PLUS]
		FROM @NIELSONINGNWData 
		WHERE SUBSTRING(VALUE,11,1)=0
		AND SUBSTRING(VALUE,42,2)=00
		AND (SUBSTRING(VALUE,97,1)=NULL 
		OR (SUBSTRING(VALUE,97,1)=''))
		--AND SUBSTRING(VALUE,DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','Quarter Hour Identifier'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','Quarter Hour Identifier'),1))>0
		AND SUBSTRING(VALUE,85,1)='P'
		--AND CONVERT(INT, SUBSTRING(VALUE,DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','Program Put Indicator'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','Program Put Indicator'),1)))=0;
		AND Convert(int,SUBSTRING(VALUE,86,4))<2400

		--INSERT FILTERED DEMOGRAPHIC DATA.
		INSERT INTO @DMCALCULATEDDATA(NETWORKCODE,AIRDATE,QUARTERHOURIDENTIFIER,DEMOGRAPHICGROUPID,FC2_5,FC6_8,FC9_11,FT12_14,FT15_17,F18_20,F21_24,F25_29,
		F30_34,F35_39,F40_44,F45_49,F50_54,F55_64,F65PLUS,MC2_5,MC6_8,MC9_11,MT12_14,MT15_17,
		M18_20,M21_24,M25_29,M30_34,M35_39,M40_44,M45_49,M50_54,M55_64,M65PLUS
		)
		SELECT  DD.NETWORKCODE,DD.AIRDATE,DD.QUARTERHOURIDENTIFIER,DD.DEMOGRAPHICGROUPID,
		SUM(CONVERT(INT,ISNULL(FC2_5,0)))/@DEMOGRAPHICDIVIDER[FC2_5],
		SUM(CONVERT(INT,ISNULL(FC6_8,0)))/@DEMOGRAPHICDIVIDER[FC6_8],
		SUM(CONVERT(INT,ISNULL(FC9_11,0)))/@DEMOGRAPHICDIVIDER[FC9_11],
		SUM(CONVERT(INT,ISNULL(FT12_14,0)))/@DEMOGRAPHICDIVIDER[FT12_14],
		SUM(CONVERT(INT,ISNULL(FT15_17,0)))/@DEMOGRAPHICDIVIDER[FT15_17],
		SUM(CONVERT(INT,ISNULL(F18_20,0)))/@DEMOGRAPHICDIVIDER[F18_20],
		SUM(CONVERT(INT,ISNULL(F21_24,0)))/@DEMOGRAPHICDIVIDER[F21_24],
		SUM(CONVERT(INT,ISNULL(F25_29,0)))/@DEMOGRAPHICDIVIDER[F25_29],
		SUM(CONVERT(INT,ISNULL(F30_34,0)))/@DEMOGRAPHICDIVIDER[F30_34],
		SUM(CONVERT(INT,ISNULL(F35_39,0)))/@DEMOGRAPHICDIVIDER[F35_39],
		SUM(CONVERT(INT,ISNULL(F40_44,0)))/@DEMOGRAPHICDIVIDER[F40_44],
		SUM(CONVERT(INT,ISNULL(F45_49,0)))/@DEMOGRAPHICDIVIDER[F45_49],
		SUM(CONVERT(INT,ISNULL(F50_54,0)))/@DEMOGRAPHICDIVIDER[F50_54],
		SUM(CONVERT(INT,ISNULL(F55_64,0)))/@DEMOGRAPHICDIVIDER[F55_64],
		SUM(CONVERT(INT,ISNULL(F65PLUS,0)))/@DEMOGRAPHICDIVIDER[F65PLUS],
		SUM(CONVERT(INT,ISNULL(MC2_5,0)))/@DEMOGRAPHICDIVIDER[MC2_5],
		SUM(CONVERT(INT,ISNULL(MC6_8,0)))/@DEMOGRAPHICDIVIDER[MC6_8],
		SUM(CONVERT(INT,ISNULL(MC9_11,0)))/@DEMOGRAPHICDIVIDER[MC9_11],
		SUM(CONVERT(INT,ISNULL(MT12_14,0)))/@DEMOGRAPHICDIVIDER[MT12_14],
		SUM(CONVERT(INT,ISNULL(MT15_17,0)))/@DEMOGRAPHICDIVIDER[MT15_17],
		SUM(CONVERT(INT,ISNULL(M18_20,0)))/@DEMOGRAPHICDIVIDER[M18_20],
		SUM(CONVERT(INT,ISNULL(M21_24,0)))/@DEMOGRAPHICDIVIDER[M21_24],
		SUM(CONVERT(INT,ISNULL(M25_29,0)))/@DEMOGRAPHICDIVIDER[M25_29],
		SUM(CONVERT(INT,ISNULL(M30_34,0)))/@DEMOGRAPHICDIVIDER[M30_34],
		SUM(CONVERT(INT,ISNULL(M35_39,0)))/@DEMOGRAPHICDIVIDER[M35_39],
		SUM(CONVERT(INT,ISNULL(M40_44,0)))/@DEMOGRAPHICDIVIDER[M40_44],
		SUM(CONVERT(INT,ISNULL(M45_49,0)))/@DEMOGRAPHICDIVIDER[M45_49],
		SUM(CONVERT(INT,ISNULL(M50_54,0)))/@DEMOGRAPHICDIVIDER[M50_54],
		SUM(CONVERT(INT,ISNULL(M55_64,0)))/@DEMOGRAPHICDIVIDER[M55_64],
		SUM(CONVERT(INT,ISNULL(M65PLUS,0)))/@DEMOGRAPHICDIVIDER[M65PLUS]
		 FROM 
		@DMFILTEREDDATA DD
		GROUP BY DD.NETWORKCODE,DD.AIRDATE,DD.QUARTERHOURIDENTIFIER,DD.DEMOGRAPHICGROUPID

		--INSERT INTO FINAL RATING TABLE

		INSERT INTO NLSNNetworkAndCableProgramRating([StationID],[AirDT],StartTime,EndTime,HouseHold,National_FC2_5,National_FC6_8,National_FC9_11,National_FT12_14,National_FT15_17,National__F18_20,
		National_F21_24,National_F25_29,National_F30_34,National_F35_39,National_F40_44,National_F45_49,National_F50_54,National_F55_64,National_F65PLUS,National_MC2_5,National_MC6_8,National_MC9_11,
		National_MT12_14,National_MT15_17,National_M18_20,National_M21_24,National_M25_29,National_M30_34,National_M35_39,National_M40_44,National_M45_49,National_M50_54,National_M55_64,National_M65PLUS)

		SELECT HR.ACNNETWORKCODE,convert(datetime,'20'+substring(HR.AIRDATE,2,6))[AirDate],cast(convert(datetime,SUBSTRING(HR.STARTTIME,1,2)+':'+SUBSTRING(HR.STARTTIME,3,2)) as time)[StartTime],
		cast(convert(datetime,SUBSTRING(HR.ENDTIME,1,2)+':'+SUBSTRING(HR.ENDTIME,3,2)+':'+SUBSTRING(HR.ENDTIME,5,2)) as time)[EndTime],HOUSEHOLDVALUE,
		case when DD.DEMOGRAPHICGROUPID='001' then FC2_5
		     when DD.DEMOGRAPHICGROUPID='021' then (select TOP 1 FC2_5 FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER-1)) END
		[FC2_5],
		case when DD.DEMOGRAPHICGROUPID='001' then FC6_8
		     when DD.DEMOGRAPHICGROUPID='021' then (select TOP 1 FC6_8 FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER-1)) END
		[FC6_8]
    	,
		case when DD.DEMOGRAPHICGROUPID='001' then FC9_11
		     when DD.DEMOGRAPHICGROUPID='021' then (select TOP 1 FC9_11 FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER-1)) END
		[FC9_11]		
		,
		case when DD.DEMOGRAPHICGROUPID='001' then FT12_14
		     when DD.DEMOGRAPHICGROUPID='021' then (select TOP 1 FT12_14 FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER-1)) END
		[FT12_14]
		,
		case when DD.DEMOGRAPHICGROUPID='001' then FT15_17
		     when DD.DEMOGRAPHICGROUPID='021' then (select TOP 1 FT15_17 FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER-1)) END
		[FT15_17],
		case when DD.DEMOGRAPHICGROUPID='001' then F18_20
		     when DD.DEMOGRAPHICGROUPID='021' then (select TOP 1 F18_20 FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER-1)) END
		[F18_20],
		case when DD.DEMOGRAPHICGROUPID='001' then F21_24
		     when DD.DEMOGRAPHICGROUPID='021' then (select TOP 1 F21_24 FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER-1)) END
		[F21_24],
		case when DD.DEMOGRAPHICGROUPID='001' then F25_29
		     when DD.DEMOGRAPHICGROUPID='021' then (select TOP 1 F25_29 FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER-1)) END
		[F25_29],
		case when DD.DEMOGRAPHICGROUPID='001' then F30_34
		     when DD.DEMOGRAPHICGROUPID='021' then (select TOP 1 F30_34 FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER-1)) END
		[F30_34],
		case when DD.DEMOGRAPHICGROUPID='001' then F35_39
		     when DD.DEMOGRAPHICGROUPID='021' then (select TOP 1 F35_39 FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER-1)) END
		[F35_39],
		case when DD.DEMOGRAPHICGROUPID='001' then F40_44
		     when DD.DEMOGRAPHICGROUPID='021' then (select TOP 1 F40_44 FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER-1)) END
		[F40_44],
		case when DD.DEMOGRAPHICGROUPID='001' then F45_49
		     when DD.DEMOGRAPHICGROUPID='021' then (select TOP 1 F45_49 FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER-1)) END
		[F45_49],
		case when DD.DEMOGRAPHICGROUPID='001' then F50_54
		     when DD.DEMOGRAPHICGROUPID='021' then (select TOP 1 F50_54 FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER-1)) END
		[F50_54],
		case when DD.DEMOGRAPHICGROUPID='001' then F55_64
		     when DD.DEMOGRAPHICGROUPID='021' then (select TOP 1 F55_64 FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER-1)) END		
		[F55_64],
		case when DD.DEMOGRAPHICGROUPID='001' then F65PLUS
		     when DD.DEMOGRAPHICGROUPID='021' then (select TOP 1 F65PLUS FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER-1)) END		
		[F65PLUS],
		case when DD.DEMOGRAPHICGROUPID='001' then MC2_5
		     when DD.DEMOGRAPHICGROUPID='021' then (select TOP 1 MC2_5 FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER-1)) END
		[MC2_5],
		case when DD.DEMOGRAPHICGROUPID='001' then MC6_8
		     when DD.DEMOGRAPHICGROUPID='021' then (select TOP 1 MC6_8 FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER-1)) END
		[MC6_8],
		case when DD.DEMOGRAPHICGROUPID='001' then MC9_11
		     when DD.DEMOGRAPHICGROUPID='021' then (select TOP 1 MC9_11 FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER-1)) END
		[MC9_11],
		case when DD.DEMOGRAPHICGROUPID='001' then MT12_14
		     when DD.DEMOGRAPHICGROUPID='021' then (select TOP 1 MT12_14 FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER-1)) END
		MT12_14,
		case when DD.DEMOGRAPHICGROUPID='001' then MT15_17
		     when DD.DEMOGRAPHICGROUPID='021' then (select TOP 1 MT15_17 FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER-1)) END
		[MT15_17],
		case when DD.DEMOGRAPHICGROUPID='021' then M18_20
		     when DD.DEMOGRAPHICGROUPID='001' then (select TOP 1 M18_20 FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER+1)) END
		[M18_20],
		case when DD.DEMOGRAPHICGROUPID='021' then M21_24
		     when DD.DEMOGRAPHICGROUPID='001' then (select TOP 1 M21_24 FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER+1)) END		
		[M21_24],
		case when DD.DEMOGRAPHICGROUPID='021' then M25_29
		     when DD.DEMOGRAPHICGROUPID='001' then (select TOP 1 M25_29 FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER+1)) END
		[M25_29],
		case when DD.DEMOGRAPHICGROUPID='021' then M30_34
		     when DD.DEMOGRAPHICGROUPID='001' then (select TOP 1 M30_34 FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER+1)) END		
		[M30_34],
		case when DD.DEMOGRAPHICGROUPID='021' then M35_39
		     when DD.DEMOGRAPHICGROUPID='001' then (select TOP 1 M35_39 FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER+1)) END
		[M35_39],
		case when DD.DEMOGRAPHICGROUPID='021' then M40_44
		     when DD.DEMOGRAPHICGROUPID='001' then (select TOP 1 M40_44 FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER+1)) END
		[M40_44],
		case when DD.DEMOGRAPHICGROUPID='021' then M45_49
		     when DD.DEMOGRAPHICGROUPID='001' then (select TOP 1 M45_49 FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER+1)) END
		[M45_49],
		case when DD.DEMOGRAPHICGROUPID='021' then M50_54
		     when DD.DEMOGRAPHICGROUPID='001' then (select TOP 1 M50_54 FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER+1)) END
		[M50_54]
		,
		case when DD.DEMOGRAPHICGROUPID='021' then M55_64
		     when DD.DEMOGRAPHICGROUPID='001' then (select TOP 1 M55_64 FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER+1)) END		
		[M55_64],
		case when DD.DEMOGRAPHICGROUPID='021' then M65PLUS 
		     when DD.DEMOGRAPHICGROUPID='001' then (select TOP 1 M65PLUS  FROM @DMCALCULATEDDATA WHERE NETWORKCODE=HR.ACNNETWORKCODE
		AND AIRDATE=HR.AIRDATE AND QUARTERHOURIDENTIFIER=(DD.QUARTERHOURIDENTIFIER+1)) END
		[M65PLUS]		
		--FC2_5,FC6_8,FC9_11,FT12_14,FT15_17,F18_20,
		--F21_24,F25_29,F30_34,F35_39,F40_44,F45_49,F50_54,F55_64,F65PLUS,MC2_5,MC6_8,MC9_11,
		--MT12_14,MT15_17,M18_20,M21_24,M25_29,M30_34,M35_39,M40_44,M45_49,M50_54,M55_64,M65PLUS 
		FROM @HHFINALRESULT HR
		INNER JOIN @DMCALCULATEDDATA DD ON DD.NETWORKCODE=HR.ACNNETWORKCODE
		AND DD.AIRDATE=HR.AIRDATE AND HR.QUARTERHOURIDENTIFIER=DD.QUARTERHOURIDENTIFIER
		ORDER BY HR.ACNNETWORKCODE,HR.AIRDATE,HR.STARTTIME
       
	    SELECT Count(*)[ImportedRecCount] 
        FROM   NLSNNetworkAndCableProgramRating 
        --  WHERE  AirDate = @BatchID 

          COMMIT TRANSACTION 
      END try 

      BEGIN catch 
          DECLARE @error   INT, 
                  @message VARCHAR(4000), 
                  @lineNo  INT 

          SELECT @error = Error_number(), 
                 @message = Error_message(), 
                 @lineNo = Error_line() 

          RAISERROR ('sp_NIELSONInsertNRTProgramNWFileData: %d: %s',16,1,@error,@message, 
                     @lineNo 
          ); 

          ROLLBACK TRANSACTION 
      END catch; 
  END;