CREATE PROC TESTNIELSONQUERY
AS
BEGIN
--Table variable to hold filtered household data.
DECLARE @HHFILTEREDData TABLE
(
  ACNNETWORKCODE VARCHAR(50), 
  AIRDATE VARCHAR(50),
  STARTTIME VARCHAR(50),
  ENDTIME VARCHAR(50),
  FIRSTQUARTERHOURDURATION VARCHAR(50),
  SECONDQUARTERHOURDURATION VARCHAR(50),
  HHFIRST VARCHAR(50),
  HHSECOND VARCHAR(50),
  HalfHourIdentifier VARCHAR(50)
);
--Table variable to hold filtered household calculated data.
DECLARE @HHCALCULATIONRESULT TABLE
(
  ACNNETWORKCODE VARCHAR(50), 
  AIRDATE VARCHAR(50),
  HalfHourIdentifier VARCHAR(50),
  HHFIRST VARCHAR(50),
  HHSECOND VARCHAR(50),
  QUARTERHOURIDENTIFIER VARCHAR(50),
  STARTTIME VARCHAR(50)
);
--Table variable to hold final household data.
DECLARE @HHFINALRESULT TABLE
(
  ACNNETWORKCODE VARCHAR(50), 
  AIRDATE VARCHAR(50),
  STARTTIME VARCHAR(50),
  HalfHourIdentifier VARCHAR(50),
  QUARTERHOURIDENTIFIER VARCHAR(50),
  HOUSEHOLDVALUE BIGINT
  );

DECLARE @DOUBLE TABLE
(
  SlNo INT
);


INSERT INTO @DOUBLE(SlNo)
SELECT SlNo
FROM (
select 1[SlNo]
union
select 2[SlNo]
)AS FILTER;

---DEMOGRAPHIC VARIABLES---

DECLARE @DMFILTEREDDATA TABLE
(
  NETWORKCODE VARCHAR(50), 
  AIRDATE VARCHAR(50),
  STARTTIME VARCHAR(50),
  ENDTIME VARCHAR(50),
  QUARTERHOURIDENTIFIER VARCHAR(50),
  DEMOGRAPHICGROUPID VARCHAR(50),
  FC2_5 VARCHAR(50),
  FC6_8 VARCHAR(50),
  FC9_11 VARCHAR(50),
  FT12_14 VARCHAR(50),
  FT15_17 VARCHAR(50),
  F18_20 VARCHAR(50),
  F21_24 VARCHAR(50),
  F25_29 VARCHAR(50),
  F30_34 VARCHAR(50),
  F35_39 VARCHAR(50),
  F40_44 VARCHAR(50),
  F45_49 VARCHAR(50),
  F50_54 VARCHAR(50),
  F55_64 VARCHAR(50),
  F65PLUS VARCHAR(50),
  MC2_5 VARCHAR(50),
  MC6_8 VARCHAR(50),
  MC9_11 VARCHAR(50),
  MT12_14 VARCHAR(50),
  MT15_17 VARCHAR(50),
  M18_20 VARCHAR(50),
  M21_24 VARCHAR(50),
  M25_29 VARCHAR(50),
  M30_34 VARCHAR(50),
  M35_39 VARCHAR(50),
  M40_44 VARCHAR(50),
  M45_49 VARCHAR(50),
  M50_54 VARCHAR(50),
  M55_64 VARCHAR(50),
  M65PLUS VARCHAR(50)
  );

DECLARE @DMCALCULATEDDATA TABLE
(
  NETWORKCODE VARCHAR(50), 
  AIRDATE VARCHAR(50),
  QUARTERHOURIDENTIFIER VARCHAR(50),
  DEMOGRAPHICGROUPID VARCHAR(50),
  FC2_5 VARCHAR(50),
  FC6_8 VARCHAR(50),
  FC9_11 VARCHAR(50),
  FT12_14 VARCHAR(50),
  FT15_17 VARCHAR(50),
  F18_20 VARCHAR(50),
  F21_24 VARCHAR(50),
  F25_29 VARCHAR(50),
  F30_34 VARCHAR(50),
  F35_39 VARCHAR(50),
  F40_44 VARCHAR(50),
  F45_49 VARCHAR(50),
  F50_54 VARCHAR(50),
  F55_64 VARCHAR(50),
  F65PLUS VARCHAR(50),
  MC2_5 VARCHAR(50),
  MC6_8 VARCHAR(50),
  MC9_11 VARCHAR(50),
  MT12_14 VARCHAR(50),
  MT15_17 VARCHAR(50),
  M18_20 VARCHAR(50),
  M21_24 VARCHAR(50),
  M25_29 VARCHAR(50),
  M30_34 VARCHAR(50),
  M35_39 VARCHAR(50),
  M40_44 VARCHAR(50),
  M45_49 VARCHAR(50),
  M50_54 VARCHAR(50),
  M55_64 VARCHAR(50),
  M65PLUS VARCHAR(50)
  );

  DECLARE @DEMOGRAPHICDIVIDER AS INT;
  SET @DEMOGRAPHICDIVIDER=30;


---INSERT HOUSEHOLD FILTERED DATA.

INSERT INTO @HHFILTEREDData(ACNNETWORKCODE,AIRDATE,STARTTIME,FIRSTQUARTERHOURDURATION,SECONDQUARTERHOURDURATION,ENDTIME,HHFIRST,HHSECOND,HalfHourIdentifier)

SELECT 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRHouseholdData','Channel/Station'),DBO.GetEndIndexCntOfNLSNINGAttribute('NPRHouseholdData','Channel/Station'))[ACNNETWORKCODE],
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRHouseholdData','Air Date'),DBO.GetEndIndexCntOfNLSNINGAttribute('NPRHouseholdData','Air Date'))[AIRDATE], 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRHouseholdData','Start Time'),DBO.GetEndIndexCntOfNLSNINGAttribute('NPRHouseholdData','Start Time'))[STARTTIME],
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRHouseholdData','First Quarter-Hr Contributing Duration'),DBO.GetEndIndexCntOfNLSNINGAttribute('NPRHouseholdData','First Quarter-Hr Contributing Duration'))[FIRSTQUARTERHOURDURATION],
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRHouseholdData','Second Quarter-Hr Contributing Duration'),DBO.GetEndIndexCntOfNLSNINGAttribute('NPRHouseholdData','Second Quarter-Hr Contributing Duration'))[SECONDQUARTERHOURDURATION],
''[ENDTIME],
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRHouseholdData','HHFirst'),DBO.GetEndIndexCntOfNLSNINGAttribute('NPRHouseholdData','HHFirst'))[HHFIRST], 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRHouseholdData','HHSecond'),DBO.GetEndIndexCntOfNLSNINGAttribute('NPRHouseholdData','HHSecond'))[HHSECOND],
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRHouseholdData','Half Hour Identifier'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRHouseholdData','Half Hour Identifier'),1))[HalfHourIdentifier]
FROM
[ProgramNetworkData] PN
WHERE SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRHouseholdData','Original/Correction'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRHouseholdData','Original/Correction'),1))=0
AND SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRHouseholdData','Number of Days/Weeks'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRHouseholdData','Number of Days/Weeks'),1))=00
AND (SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRHouseholdData','Program VCR Indicator'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRHouseholdData','Program VCR Indicator'),1))=NULL 
OR (SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRHouseholdData','Program VCR Indicator'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRHouseholdData','Program VCR Indicator'),1))=''))
--AND SUBSTRING(VALUE,DBO.GetStartIndexOfNLSNINGAttribute('NPRHouseholdData','Half Hour Identifier'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRHouseholdData','Half Hour Identifier'),1))>0
AND SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRHouseholdData','Record Type'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRHouseholdData','Record Type'),1))='H';

--INSERT HOUSEHOLD CALCULATED DATA.

INSERT INTO @HHCALCULATIONRESULT(ACNNETWORKCODE,AIRDATE,HalfHourIdentifier,HHFIRST,HHSECOND,QUARTERHOURIDENTIFIER,STARTTIME)

SELECT ACNNETWORKCODE,AIRDATE,HALFHOURIDENTIFIER,HHFIRST,HHSECOND,
(SELECT QuarterHourID from QuarterHour q WHERE cast(convert(datetime,SUBSTRING(FILTER.STARTTIME,1,2)+':'+SUBSTRING(FILTER.STARTTIME,3,2)) as time) BETWEEN q.StartTime and q.EndTime )[QUARTERHOURIDENTIFIER],
STARTTIME
 FROM 
(select CD.ACNNETWORKCODE,CD.AIRDATE,CD.HalfHourIdentifier,count(*)[Count],
(sum(isnull(convert(bigint,CD.FIRSTQUARTERHOURDURATION),0)*isnull(CD.HHFIRST,0))/sum(convert(bigint,CD.FIRSTQUARTERHOURDURATION)))[HHFIRST],
(sum(isnull(convert(bigint,CD.SECONDQUARTERHOURDURATION),0)*isnull(CD.HHSECOND,0))/sum(convert(bigint,CD.SECONDQUARTERHOURDURATION)))[HHSECOND],
(SELECT TOP 1 STARTTIME FROM @HHFILTEREDData WHERE ACNNETWORKCODE=CD.ACNNETWORKCODE AND AIRDATE=CD.AIRDATE AND HalfHourIdentifier=CD.HalfHourIdentifier)[STARTTIME] 
from @HHFILTEREDData CD
WHERE CD.FIRSTQUARTERHOURDURATION<>0 AND CD.SECONDQUARTERHOURDURATION<>0
AND Convert(int,CD.STARTTIME)<2400
group by ACNNETWORKCODE,AIRDATE,HalfHourIdentifier
) FILTER;

--INSERT FINAL HOUSE HOLD RESULT DATA.

INSERT INTO @HHFINALRESULT(ACNNETWORKCODE,AIRDATE,STARTTIME,HalfHourIdentifier,QUARTERHOURIDENTIFIER,HOUSEHOLDVALUE)

SELECT CR.ACNNETWORKCODE,CR.AIRDATE,CR.STARTTIME,CR.HALFHOURIDENTIFIER,(CASE WHEN CD.SLNO=1 THEN CR.QUARTERHOURIDENTIFIER WHEN CD.SLNO=2 THEN CR.QUARTERHOURIDENTIFIER+1 END)[QUARTERHOURIDENTIFIER] 
,(CASE WHEN CD.SLNO=1 THEN CR.HHFIRST WHEN CD.SLNO=2 THEN CR.HHSECOND END)[HOUSEHOLDVALUE] FROM 
@HHCALCULATIONRESULT CR,
@DOUBLE CD


--INSERT FILTERED DEMOGRAPHIC DATA.
INSERT INTO @DMFILTEREDDATA(NETWORKCODE,AIRDATE,STARTTIME,ENDTIME,QUARTERHOURIDENTIFIER,DEMOGRAPHICGROUPID,FC2_5,FC6_8,FC9_11,FT12_14,FT15_17,F18_20,F21_24,F25_29,
F30_34,F35_39,F40_44,F45_49,F50_54,F55_64,F65PLUS,MC2_5,MC6_8,MC9_11,MT12_14,MT15_17,
M18_20,M21_24,M25_29,M30_34,M35_39,M40_44,M45_49,M50_54,M55_64,M65PLUS
)

SELECT SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','ChannelOrStation'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','ChannelOrStation'),1))[NETWORKCODE],
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','AIR DATE'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','AIR DATE'),1))[AIRDATE], 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','Start Time'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','Start Time'),1))[STARTTIME],
''[ENDTIME],
CASE WHEN SUBSTRING([Value],92,3)='001' THEN 
(SELECT QuarterHourID from QuarterHour 
WHERE cast(convert(datetime,SUBSTRING((SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','Start Time'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','Start Time'),1))),1,2)+':'+
SUBSTRING((SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','Start Time'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','Start Time'),1))),3,2)) as time) 
BETWEEN StartTime and EndTime )
WHEN SUBSTRING([Value],92,3)='021' THEN (SELECT QuarterHourID+1 from QuarterHour 
WHERE cast(convert(datetime,SUBSTRING((SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','Start Time'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','Start Time'),1))),1,2)+':'+
SUBSTRING((SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','Start Time'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','Start Time'),1))),3,2)) as time) 
BETWEEN StartTime and EndTime ) END
[QUARTERHOURIDENTIFIER],
--SUBSTRING(VALUE,DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','Quarter Hour Identifier'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','Quarter Hour Identifier'),1))[QUARTERHOURIDENTIFIER],
SUBSTRING([Value],92,3)[DEMOGRAPHICGROUPID],
CASE WHEN SUBSTRING([Value],92,3)='001' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','FC2_5'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','FC2_5'),1))
END [FC2_5],
CASE WHEN SUBSTRING([Value],92,3)='001' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','FC6_8'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','FC6_8'),1))
END[FC6_8],
CASE WHEN SUBSTRING([Value],92,3)='001' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','FC9_11'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','FC9_11'),1))
END[FC9_11],
CASE WHEN SUBSTRING([Value],92,3)='001' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','FT12_14'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','FT12_14'),1))
END[FT12_14],
CASE WHEN SUBSTRING([Value],92,3)='001' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','FT15_17'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','FT15_17'),1))
END[FT15_17],
CASE WHEN SUBSTRING([Value],92,3)='001' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','F18_20'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','F18_20'),1))
END[F18_20],
CASE WHEN SUBSTRING([Value],92,3)='001' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','F21_24'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','F21_24'),1))
END[F21_24],
CASE WHEN SUBSTRING([Value],92,3)='001' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','F25_29'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','F25_29'),1))
END[F25_29],
CASE WHEN SUBSTRING([Value],92,3)='001' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','F30_34'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','F30_34'),1))
END[F30_34],
CASE WHEN SUBSTRING([Value],92,3)='001' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','F35_39'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','F35_39'),1))
END[F35_39],
CASE WHEN SUBSTRING([Value],92,3)='001' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','F40_44'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','F40_44'),1))
END[F40_44],
CASE WHEN SUBSTRING([Value],92,3)='001' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','F45_49'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','F45_49'),1))
END[F45_49],
CASE WHEN SUBSTRING([Value],92,3)='001' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','F50_54'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','F50_54'),1))
END[F50_54],
CASE WHEN SUBSTRING([Value],92,3)='001' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','F55_64'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','F55_64'),1))
END[F55_64],
CASE WHEN SUBSTRING([Value],92,3)='001' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','F65PLUS'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','F65PLUS'),1))
END[F65PLUS],
CASE WHEN SUBSTRING([Value],92,3)='001' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','MC2_5'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','MC2_5'),1))
END[MC2_5],
CASE WHEN SUBSTRING([Value],92,3)='001' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','MC6_8'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','MC6_8'),1))
END[MC6_8],
CASE WHEN SUBSTRING([Value],92,3)='001' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','MC9_11'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','MC9_11'),1))
END[MC9_11],
CASE WHEN SUBSTRING([Value],92,3)='001' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','MT12_14'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','MT12_14'),1))
END[MT12_14],
CASE WHEN SUBSTRING([Value],92,3)='001' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','MT12_14'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','MT12_14'),1))
END[MT15_17],
CASE WHEN SUBSTRING([Value],92,3)='021' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','M18_20'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','M18_20'),1))
END[M18_20],
CASE WHEN SUBSTRING([Value],92,3)='021' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','M21_24'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','M21_24'),1))
END[M21_24],
CASE WHEN SUBSTRING([Value],92,3)='021' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','M25_29'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','M25_29'),1))
END[M25_29],
CASE WHEN SUBSTRING([Value],92,3)='021' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','M30_34'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','M30_34'),1))
END[M30_34],
CASE WHEN SUBSTRING([Value],92,3)='021' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','M35_39'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','M35_39'),1))
END[M35_39],
CASE WHEN SUBSTRING([Value],92,3)='021' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','M40_44'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','M40_44'),1))
END[M40_44],
CASE WHEN SUBSTRING([Value],92,3)='021' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','M45_49'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','M45_49'),1))
END[M45_49],
CASE WHEN SUBSTRING([Value],92,3)='021' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','M50_54'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','M50_54'),1))
END[M50_54],
CASE WHEN SUBSTRING([Value],92,3)='021' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','M55_64'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','M55_64'),1))
END[M55_64],
CASE WHEN SUBSTRING([Value],92,3)='021' THEN 
SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','M65PLUS'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','M65PLUS'),1))
END[M65PLUS]
FROM [ProgramNetworkData] 
WHERE SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','Original/Correction'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','Original/Correction'),1))=0
AND SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','Number of Days/Weeks'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','Number of Days/Weeks'),1))=00
AND (SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','Program VCR Indicator'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','Program VCR Indicator'),1))=NULL 
OR (SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','Program VCR Indicator'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','Program VCR Indicator'),1))=''))
--AND SUBSTRING(VALUE,DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','Quarter Hour Identifier'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','Quarter Hour Identifier'),1))>0
AND SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','Record Type'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','Record Type'),1))='P'
--AND CONVERT(INT, SUBSTRING(VALUE,DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','Program Put Indicator'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','Program Put Indicator'),1)))=0;
AND Convert(int,SUBSTRING([Value],DBO.GetStartIndexOfNLSNINGAttribute('NPRDemographicData','Start Time'),ISNULL(DBO.GetEndIndexCntOfNLSNINGAttribute('NPRDemographicData','Start Time'),1)))<2400

--INSERT FILTERED DEMOGRAPHIC DATA.
INSERT INTO @DMCALCULATEDDATA(NETWORKCODE,AIRDATE,QUARTERHOURIDENTIFIER,DEMOGRAPHICGROUPID,FC2_5,FC6_8,FC9_11,FT12_14,FT15_17,F18_20,F21_24,F25_29,
F30_34,F35_39,F40_44,F45_49,F50_54,F55_64,F65PLUS,MC2_5,MC6_8,MC9_11,MT12_14,MT15_17,
M18_20,M21_24,M25_29,M30_34,M35_39,M40_44,M45_49,M50_54,M55_64,M65PLUS
)

SELECT  DD.NETWORKCODE,DD.AIRDATE,DD.QUARTERHOURIDENTIFIER,DD.DEMOGRAPHICGROUPID,
SUM(CONVERT(INT,ISNULL(FC2_5,0)))/@DEMOGRAPHICDIVIDER[FC2_5],
SUM(CONVERT(INT,ISNULL(FC6_8,0)))/@DEMOGRAPHICDIVIDER[FC6_8],
SUM(CONVERT(INT,ISNULL(FC9_11,0)))/@DEMOGRAPHICDIVIDER[FC9_11],
SUM(CONVERT(INT,ISNULL(FT12_14,0)))/@DEMOGRAPHICDIVIDER[FT12_14],
SUM(CONVERT(INT,ISNULL(FT15_17,0)))/@DEMOGRAPHICDIVIDER[FT15_17],
SUM(CONVERT(INT,ISNULL(F18_20,0)))/@DEMOGRAPHICDIVIDER[F18_20],
SUM(CONVERT(INT,ISNULL(F21_24,0)))/@DEMOGRAPHICDIVIDER[F21_24],
SUM(CONVERT(INT,ISNULL(F25_29,0)))/@DEMOGRAPHICDIVIDER[F25_29],
SUM(CONVERT(INT,ISNULL(F30_34,0)))/@DEMOGRAPHICDIVIDER[F30_34],
SUM(CONVERT(INT,ISNULL(F35_39,0)))/@DEMOGRAPHICDIVIDER[F35_39],
SUM(CONVERT(INT,ISNULL(F40_44,0)))/@DEMOGRAPHICDIVIDER[F40_44],
SUM(CONVERT(INT,ISNULL(F45_49,0)))/@DEMOGRAPHICDIVIDER[F45_49],
SUM(CONVERT(INT,ISNULL(F50_54,0)))/@DEMOGRAPHICDIVIDER[F50_54],
SUM(CONVERT(INT,ISNULL(F55_64,0)))/@DEMOGRAPHICDIVIDER[F55_64],
SUM(CONVERT(INT,ISNULL(F65PLUS,0)))/@DEMOGRAPHICDIVIDER[F65PLUS],
SUM(CONVERT(INT,ISNULL(MC2_5,0)))/@DEMOGRAPHICDIVIDER[MC2_5],
SUM(CONVERT(INT,ISNULL(MC6_8,0)))/@DEMOGRAPHICDIVIDER[MC6_8],
SUM(CONVERT(INT,ISNULL(MC9_11,0)))/@DEMOGRAPHICDIVIDER[MC9_11],
SUM(CONVERT(INT,ISNULL(MT12_14,0)))/@DEMOGRAPHICDIVIDER[MT12_14],
SUM(CONVERT(INT,ISNULL(MT15_17,0)))/@DEMOGRAPHICDIVIDER[MT15_17],
SUM(CONVERT(INT,ISNULL(M18_20,0)))/@DEMOGRAPHICDIVIDER[M18_20],
SUM(CONVERT(INT,ISNULL(M21_24,0)))/@DEMOGRAPHICDIVIDER[M21_24],
SUM(CONVERT(INT,ISNULL(M25_29,0)))/@DEMOGRAPHICDIVIDER[M25_29],
SUM(CONVERT(INT,ISNULL(M30_34,0)))/@DEMOGRAPHICDIVIDER[M30_34],
SUM(CONVERT(INT,ISNULL(M35_39,0)))/@DEMOGRAPHICDIVIDER[M35_39],
SUM(CONVERT(INT,ISNULL(M40_44,0)))/@DEMOGRAPHICDIVIDER[M40_44],
SUM(CONVERT(INT,ISNULL(M45_49,0)))/@DEMOGRAPHICDIVIDER[M45_49],
SUM(CONVERT(INT,ISNULL(M50_54,0)))/@DEMOGRAPHICDIVIDER[M50_54],
SUM(CONVERT(INT,ISNULL(M55_64,0)))/@DEMOGRAPHICDIVIDER[M55_64],
SUM(CONVERT(INT,ISNULL(M65PLUS,0)))/@DEMOGRAPHICDIVIDER[M65PLUS]
 FROM 
@DMFILTEREDDATA DD
GROUP BY DD.NETWORKCODE,DD.AIRDATE,DD.QUARTERHOURIDENTIFIER,DD.DEMOGRAPHICGROUPID


SELECT HR.ACNNETWORKCODE,HR.AIRDATE,HR.STARTTIME,'',HOUSEHOLDVALUE,FC2_5,FC6_8,FC9_11,FT12_14,FT15_17,F18_20,F21_24,F25_29,
F30_34,F35_39,F40_44,F45_49,F50_54,F55_64,F65PLUS,MC2_5,MC6_8,MC9_11,MT12_14,MT15_17,
M18_20,M21_24,M25_29,M30_34,M35_39,M40_44,M45_49,M50_54,M55_64,M65PLUS FROM @HHFINALRESULT HR
INNER JOIN @DMCALCULATEDDATA DD ON DD.NETWORKCODE=HR.ACNNETWORKCODE
AND DD.AIRDATE=HR.AIRDATE AND HR.QUARTERHOURIDENTIFIER=DD.QUARTERHOURIDENTIFIER
ORDER BY HR.ACNNETWORKCODE,HR.AIRDATE,HR.STARTTIME

END