create  proc VIEWNIELSONPROGRAMSYNDICATIONDATA
AS
BEGIN
select 
SUBSTRING(VALUE,21,10)[ACN Program Code],
SUBSTRING(VALUE,282,7)[Air Date],
SUBSTRING(VALUE,115,25)[Program Name]
from [ProgramSyndicationData]
where SUBSTRING(VALUE,11,1)=0
AND (SUBSTRING(VALUE,97,1)=NULL OR (SUBSTRING(VALUE,97,1)=''))
AND SUBSTRING(VALUE,85,1)='D'AND SUBSTRING(VALUE,1,2)='04'



select 
SUBSTRING(VALUE,21,10)[ACN Program Code],
SUBSTRING(VALUE,180,9)[Household],
SUBSTRING(VALUE,119,7)[Air Date]
from [ProgramSyndicationData]
where SUBSTRING(VALUE,11,1)=0
and SUBSTRING(VALUE,81,2)>0
AND (SUBSTRING(VALUE,97,1)=NULL OR (SUBSTRING(VALUE,97,1)=''))
AND SUBSTRING(VALUE,85,1)='H'AND SUBSTRING(VALUE,1,2)='04'



select 
*
from [ProgramSyndicationData]
where SUBSTRING(VALUE,11,1)=0
and SUBSTRING(VALUE,81,2)=0
AND (SUBSTRING(VALUE,97,1)=NULL OR (SUBSTRING(VALUE,97,1)=''))
AND SUBSTRING(VALUE,85,1)='P'AND SUBSTRING(VALUE,1,2)='04'

END
