Create proc ViewNielsonCommercialNetworkData
as
begin
SELECT 
SUBSTRING(cnwd.[Value],15,6)[ACN Network Code],
SUBSTRING([VALUE],21,10)[ACN Program Code],
SUBSTRING([VALUE],44,7)[Air Date],
SUBSTRING([VALUE],58,10)[Telecast Number],
SUBSTRING([VALUE],86,4)[Start Time],
SUBSTRING([VALUE],278,4)[End Time],
SUBSTRING([VALUE],337,9)[Households]
FROM [CommercialNetworkData] cnwd
WHERE SUBSTRING([VALUE],11,1)=0
AND SUBSTRING([VALUE],42,2)=00
AND SUBSTRING([VALUE],97,1)='B'
AND SUBSTRING([VALUE],85,1)='C'
AND SUBSTRING([VALUE],1,2)='06'

SELECT 
SUBSTRING([VALUE],15,6)[ACN Network Code],
SUBSTRING([VALUE],21,10)[ACN Program Code],
SUBSTRING([VALUE],44,7)[Air Date],
SUBSTRING([VALUE],58,10)[Telecast Number],
SUBSTRING([VALUE],86,4)[Start Time],
SUBSTRING([VALUE],278,4)[End Time]
FROM [CommercialNetworkData]
WHERE SUBSTRING([VALUE],11,1)=0
AND SUBSTRING([VALUE],42,2)=00
AND SUBSTRING([VALUE],97,1)='B'
AND SUBSTRING([VALUE],85,1)='P'
AND SUBSTRING([VALUE],1,2)='06'

end
